<?php
/**
 * NameserverServiceApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Savvii\OpenproviderRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savvii\OpenproviderRest\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Savvii\OpenproviderRest\ApiException;
use Savvii\OpenproviderRest\Configuration;
use Savvii\OpenproviderRest\HeaderSelector;
use Savvii\OpenproviderRest\ObjectSerializer;

/**
 * NameserverServiceApi Class Doc Comment
 *
 * @category Class
 * @package  Savvii\OpenproviderRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NameserverServiceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createNameserver' => [
            'application/json',
        ],
        'deleteNameserver' => [
            'application/json',
        ],
        'getNameserver' => [
            'application/json',
        ],
        'listNameservers' => [
            'application/json',
        ],
        'updateNameserver' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createNameserver
     *
     * Create nameserver
     *
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNameserver'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Savvii\OpenproviderRest\Model\NameserverCreateNameserverResponse|\Savvii\OpenproviderRest\Model\ErrorError
     */
    public function createNameserver($body, string $contentType = self::contentTypes['createNameserver'][0])
    {
        list($response) = $this->createNameserverWithHttpInfo($body, $contentType);
        return $response;
    }

    /**
     * Operation createNameserverWithHttpInfo
     *
     * Create nameserver
     *
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNameserver'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Savvii\OpenproviderRest\Model\NameserverCreateNameserverResponse|\Savvii\OpenproviderRest\Model\ErrorError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createNameserverWithHttpInfo($body, string $contentType = self::contentTypes['createNameserver'][0])
    {
        $request = $this->createNameserverRequest($body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Savvii\OpenproviderRest\Model\NameserverCreateNameserverResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\NameserverCreateNameserverResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\NameserverCreateNameserverResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Savvii\OpenproviderRest\Model\ErrorError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\ErrorError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\ErrorError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Savvii\OpenproviderRest\Model\NameserverCreateNameserverResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\NameserverCreateNameserverResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\ErrorError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createNameserverAsync
     *
     * Create nameserver
     *
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createNameserverAsync($body, string $contentType = self::contentTypes['createNameserver'][0])
    {
        return $this->createNameserverAsyncWithHttpInfo($body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createNameserverAsyncWithHttpInfo
     *
     * Create nameserver
     *
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createNameserverAsyncWithHttpInfo($body, string $contentType = self::contentTypes['createNameserver'][0])
    {
        $returnType = '\Savvii\OpenproviderRest\Model\NameserverCreateNameserverResponse';
        $request = $this->createNameserverRequest($body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createNameserver'
     *
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createNameserverRequest($body, string $contentType = self::contentTypes['createNameserver'][0])
    {

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createNameserver'
            );
        }


        $resourcePath = '/v1beta/dns/nameservers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteNameserver
     *
     * Delete nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNameserver'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse|\Savvii\OpenproviderRest\Model\ErrorError
     */
    public function deleteNameserver($name, string $contentType = self::contentTypes['deleteNameserver'][0])
    {
        list($response) = $this->deleteNameserverWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation deleteNameserverWithHttpInfo
     *
     * Delete nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNameserver'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse|\Savvii\OpenproviderRest\Model\ErrorError, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteNameserverWithHttpInfo($name, string $contentType = self::contentTypes['deleteNameserver'][0])
    {
        $request = $this->deleteNameserverRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Savvii\OpenproviderRest\Model\ErrorError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\ErrorError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\ErrorError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\ErrorError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteNameserverAsync
     *
     * Delete nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteNameserverAsync($name, string $contentType = self::contentTypes['deleteNameserver'][0])
    {
        return $this->deleteNameserverAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteNameserverAsyncWithHttpInfo
     *
     * Delete nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteNameserverAsyncWithHttpInfo($name, string $contentType = self::contentTypes['deleteNameserver'][0])
    {
        $returnType = '\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse';
        $request = $this->deleteNameserverRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteNameserver'
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteNameserverRequest($name, string $contentType = self::contentTypes['deleteNameserver'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling deleteNameserver'
            );
        }


        $resourcePath = '/v1beta/dns/nameservers/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getNameserver
     *
     * Get nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNameserver'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Savvii\OpenproviderRest\Model\NameserverGetNameserverResponse|\Savvii\OpenproviderRest\Model\ErrorError
     */
    public function getNameserver($name, string $contentType = self::contentTypes['getNameserver'][0])
    {
        list($response) = $this->getNameserverWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation getNameserverWithHttpInfo
     *
     * Get nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNameserver'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Savvii\OpenproviderRest\Model\NameserverGetNameserverResponse|\Savvii\OpenproviderRest\Model\ErrorError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getNameserverWithHttpInfo($name, string $contentType = self::contentTypes['getNameserver'][0])
    {
        $request = $this->getNameserverRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Savvii\OpenproviderRest\Model\NameserverGetNameserverResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\NameserverGetNameserverResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\NameserverGetNameserverResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Savvii\OpenproviderRest\Model\ErrorError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\ErrorError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\ErrorError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Savvii\OpenproviderRest\Model\NameserverGetNameserverResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\NameserverGetNameserverResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\ErrorError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getNameserverAsync
     *
     * Get nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNameserverAsync($name, string $contentType = self::contentTypes['getNameserver'][0])
    {
        return $this->getNameserverAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getNameserverAsyncWithHttpInfo
     *
     * Get nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNameserverAsyncWithHttpInfo($name, string $contentType = self::contentTypes['getNameserver'][0])
    {
        $returnType = '\Savvii\OpenproviderRest\Model\NameserverGetNameserverResponse';
        $request = $this->getNameserverRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getNameserver'
     *
     * @param  string $name Nameserver name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getNameserverRequest($name, string $contentType = self::contentTypes['getNameserver'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling getNameserver'
            );
        }


        $resourcePath = '/v1beta/dns/nameservers/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listNameservers
     *
     * List nameservers
     *
     * @param  string $name Nameserver name. (optional)
     * @param  string $ip Nameserver IP. (optional)
     * @param  string $ip6 Nameserver IPv6. (optional)
     * @param  string $pattern Nameserver name search pattern. Wildcatd (*) can be used. (optional)
     * @param  int $limit Limits the number of objects in the output. (optional, default to 100)
     * @param  string $offset Used to retrieve all objects from a certain offset up to the limit. (optional)
     * @param  string $order Sorting type (asc/desc). (optional, default to 'asc')
     * @param  string $order_by Field for sorting output. Possible values: id, name. (optional, default to 'name')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listNameservers'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Savvii\OpenproviderRest\Model\NameserverListNameserversResponse|\Savvii\OpenproviderRest\Model\ErrorError
     */
    public function listNameservers($name = null, $ip = null, $ip6 = null, $pattern = null, $limit = 100, $offset = null, $order = 'asc', $order_by = 'name', string $contentType = self::contentTypes['listNameservers'][0])
    {
        list($response) = $this->listNameserversWithHttpInfo($name, $ip, $ip6, $pattern, $limit, $offset, $order, $order_by, $contentType);
        return $response;
    }

    /**
     * Operation listNameserversWithHttpInfo
     *
     * List nameservers
     *
     * @param  string $name Nameserver name. (optional)
     * @param  string $ip Nameserver IP. (optional)
     * @param  string $ip6 Nameserver IPv6. (optional)
     * @param  string $pattern Nameserver name search pattern. Wildcatd (*) can be used. (optional)
     * @param  int $limit Limits the number of objects in the output. (optional, default to 100)
     * @param  string $offset Used to retrieve all objects from a certain offset up to the limit. (optional)
     * @param  string $order Sorting type (asc/desc). (optional, default to 'asc')
     * @param  string $order_by Field for sorting output. Possible values: id, name. (optional, default to 'name')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listNameservers'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Savvii\OpenproviderRest\Model\NameserverListNameserversResponse|\Savvii\OpenproviderRest\Model\ErrorError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listNameserversWithHttpInfo($name = null, $ip = null, $ip6 = null, $pattern = null, $limit = 100, $offset = null, $order = 'asc', $order_by = 'name', string $contentType = self::contentTypes['listNameservers'][0])
    {
        $request = $this->listNameserversRequest($name, $ip, $ip6, $pattern, $limit, $offset, $order, $order_by, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Savvii\OpenproviderRest\Model\NameserverListNameserversResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\NameserverListNameserversResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\NameserverListNameserversResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Savvii\OpenproviderRest\Model\ErrorError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\ErrorError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\ErrorError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Savvii\OpenproviderRest\Model\NameserverListNameserversResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\NameserverListNameserversResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\ErrorError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listNameserversAsync
     *
     * List nameservers
     *
     * @param  string $name Nameserver name. (optional)
     * @param  string $ip Nameserver IP. (optional)
     * @param  string $ip6 Nameserver IPv6. (optional)
     * @param  string $pattern Nameserver name search pattern. Wildcatd (*) can be used. (optional)
     * @param  int $limit Limits the number of objects in the output. (optional, default to 100)
     * @param  string $offset Used to retrieve all objects from a certain offset up to the limit. (optional)
     * @param  string $order Sorting type (asc/desc). (optional, default to 'asc')
     * @param  string $order_by Field for sorting output. Possible values: id, name. (optional, default to 'name')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listNameservers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listNameserversAsync($name = null, $ip = null, $ip6 = null, $pattern = null, $limit = 100, $offset = null, $order = 'asc', $order_by = 'name', string $contentType = self::contentTypes['listNameservers'][0])
    {
        return $this->listNameserversAsyncWithHttpInfo($name, $ip, $ip6, $pattern, $limit, $offset, $order, $order_by, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listNameserversAsyncWithHttpInfo
     *
     * List nameservers
     *
     * @param  string $name Nameserver name. (optional)
     * @param  string $ip Nameserver IP. (optional)
     * @param  string $ip6 Nameserver IPv6. (optional)
     * @param  string $pattern Nameserver name search pattern. Wildcatd (*) can be used. (optional)
     * @param  int $limit Limits the number of objects in the output. (optional, default to 100)
     * @param  string $offset Used to retrieve all objects from a certain offset up to the limit. (optional)
     * @param  string $order Sorting type (asc/desc). (optional, default to 'asc')
     * @param  string $order_by Field for sorting output. Possible values: id, name. (optional, default to 'name')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listNameservers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listNameserversAsyncWithHttpInfo($name = null, $ip = null, $ip6 = null, $pattern = null, $limit = 100, $offset = null, $order = 'asc', $order_by = 'name', string $contentType = self::contentTypes['listNameservers'][0])
    {
        $returnType = '\Savvii\OpenproviderRest\Model\NameserverListNameserversResponse';
        $request = $this->listNameserversRequest($name, $ip, $ip6, $pattern, $limit, $offset, $order, $order_by, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listNameservers'
     *
     * @param  string $name Nameserver name. (optional)
     * @param  string $ip Nameserver IP. (optional)
     * @param  string $ip6 Nameserver IPv6. (optional)
     * @param  string $pattern Nameserver name search pattern. Wildcatd (*) can be used. (optional)
     * @param  int $limit Limits the number of objects in the output. (optional, default to 100)
     * @param  string $offset Used to retrieve all objects from a certain offset up to the limit. (optional)
     * @param  string $order Sorting type (asc/desc). (optional, default to 'asc')
     * @param  string $order_by Field for sorting output. Possible values: id, name. (optional, default to 'name')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listNameservers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listNameserversRequest($name = null, $ip = null, $ip6 = null, $pattern = null, $limit = 100, $offset = null, $order = 'asc', $order_by = 'name', string $contentType = self::contentTypes['listNameservers'][0])
    {










        $resourcePath = '/v1beta/dns/nameservers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name,
            'name', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ip,
            'ip', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ip6,
            'ip6', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $pattern,
            'pattern', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order,
            'order', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order_by,
            'order_by', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateNameserver
     *
     * Update nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateNameserver'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse|\Savvii\OpenproviderRest\Model\ErrorError
     */
    public function updateNameserver($name, $body, string $contentType = self::contentTypes['updateNameserver'][0])
    {
        list($response) = $this->updateNameserverWithHttpInfo($name, $body, $contentType);
        return $response;
    }

    /**
     * Operation updateNameserverWithHttpInfo
     *
     * Update nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateNameserver'] to see the possible values for this operation
     *
     * @throws \Savvii\OpenproviderRest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse|\Savvii\OpenproviderRest\Model\ErrorError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateNameserverWithHttpInfo($name, $body, string $contentType = self::contentTypes['updateNameserver'][0])
    {
        $request = $this->updateNameserverRequest($name, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Savvii\OpenproviderRest\Model\ErrorError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Savvii\OpenproviderRest\Model\ErrorError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Savvii\OpenproviderRest\Model\ErrorError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Savvii\OpenproviderRest\Model\ErrorError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateNameserverAsync
     *
     * Update nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateNameserverAsync($name, $body, string $contentType = self::contentTypes['updateNameserver'][0])
    {
        return $this->updateNameserverAsyncWithHttpInfo($name, $body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateNameserverAsyncWithHttpInfo
     *
     * Update nameserver
     *
     * @param  string $name Nameserver name (required)
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateNameserverAsyncWithHttpInfo($name, $body, string $contentType = self::contentTypes['updateNameserver'][0])
    {
        $returnType = '\Savvii\OpenproviderRest\Model\NameserverNameserverBoolResponse';
        $request = $this->updateNameserverRequest($name, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateNameserver'
     *
     * @param  string $name Nameserver name (required)
     * @param  \Savvii\OpenproviderRest\Model\NameserverNameserver $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateNameserver'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateNameserverRequest($name, $body, string $contentType = self::contentTypes['updateNameserver'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling updateNameserver'
            );
        }

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling updateNameserver'
            );
        }


        $resourcePath = '/v1beta/dns/nameservers/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
