<?php
/**
 * DomainGetDomainResponseData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Savvii\OpenproviderRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savvii\OpenproviderRest\Model;

use \ArrayAccess;
use \Savvii\OpenproviderRest\ObjectSerializer;

/**
 * DomainGetDomainResponseData Class Doc Comment
 *
 * @category Class
 * @package  Savvii\OpenproviderRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DomainGetDomainResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'domainGetDomainResponseData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'abuse_details' => '\Savvii\OpenproviderRest\Model\DomainAbuseDetails',
        'active_date' => 'string',
        'additional_data' => '\Savvii\OpenproviderRest\Model\DomainAdditionalData',
        'admin_handle' => 'string',
        'api_history' => '\Savvii\OpenproviderRest\Model\DomainApiHistory[]',
        'application_id' => 'string',
        'application_mode' => 'string',
        'application_mode_expiration_date' => 'string',
        'application_mode_title' => 'string',
        'application_notice_id' => 'string',
        'application_smd' => 'string',
        'auth_code' => 'string',
        'autorenew' => 'string',
        'billing_handle' => 'string',
        'can_renew' => 'bool',
        'comments' => 'string',
        'comments_last_changed_at' => 'string',
        'creation_date' => 'string',
        'delete_status' => 'string',
        'deleted_at' => 'string',
        'dnssec' => 'string',
        'dnssec_keys' => '\Savvii\OpenproviderRest\Model\DomainDnssecKey[]',
        'domain' => '\Savvii\OpenproviderRest\Model\DomainDomain',
        'expiration_date' => 'string',
        'hard_quarantine_expiry_date' => 'string',
        'has_active_sectigo_zone' => 'bool',
        'has_history' => 'bool',
        'history' => '\Savvii\OpenproviderRest\Model\DomainHistory[]',
        'id' => 'int',
        'internal_auth_code' => 'string',
        'is_abusive' => 'bool',
        'is_client_hold_enabled' => 'string',
        'is_deleted' => 'bool',
        'is_dnssec_enabled' => 'bool',
        'is_hosted_whois' => 'bool',
        'is_lockable' => 'bool',
        'is_locked' => 'bool',
        'is_parked' => 'bool',
        'is_premium' => 'bool',
        'is_private_whois_allowed' => 'bool',
        'is_private_whois_enabled' => 'bool',
        'is_sectigo_dns_enabled' => 'bool',
        'is_spamexperts_enabled' => 'bool',
        'last_changed' => 'string',
        'modify_owner_allowed' => 'bool',
        'name_servers' => '\Savvii\OpenproviderRest\Model\DomainNameserver[]',
        'ns_group' => 'string',
        'ns_template_id' => 'int',
        'ns_template_name' => 'string',
        'nsgroup_id' => 'int',
        'order_date' => 'string',
        'owner' => '\Savvii\OpenproviderRest\Model\DomainOwner',
        'owner_company_name' => 'string',
        'owner_handle' => 'string',
        'quarantine_expiration_date' => 'string',
        'registry_expiration_date' => 'string',
        'registry_statuses' => '\Savvii\OpenproviderRest\Model\DomainRegistryStatuses',
        'renew' => 'int',
        'renewal_date' => 'string',
        'reseller_handle' => 'string',
        'reseller_id' => 'int',
        'restorable_until' => 'string',
        'scheduled_at' => 'string',
        'scheduled_from' => 'string',
        'soft_quarantine_expiry_date' => 'string',
        'status' => 'string',
        'tech_handle' => 'string',
        'trade_allowed' => 'bool',
        'trade_auth_code_required' => 'string',
        'transfer_auth_code_required' => 'string',
        'transfer_cancel_supported' => 'bool',
        'type' => 'string',
        'unit' => 'string',
        'use_domicile' => 'bool',
        'verification_email_exp_date' => 'string',
        'verification_email_name' => 'string',
        'verification_email_status' => 'string',
        'verification_email_status_description' => 'string',
        'whois_privacy_data' => '\Savvii\OpenproviderRest\Model\DomainWhoisPrivacyData'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'abuse_details' => null,
        'active_date' => null,
        'additional_data' => null,
        'admin_handle' => null,
        'api_history' => null,
        'application_id' => null,
        'application_mode' => null,
        'application_mode_expiration_date' => null,
        'application_mode_title' => null,
        'application_notice_id' => null,
        'application_smd' => null,
        'auth_code' => null,
        'autorenew' => null,
        'billing_handle' => null,
        'can_renew' => 'boolean',
        'comments' => null,
        'comments_last_changed_at' => null,
        'creation_date' => null,
        'delete_status' => null,
        'deleted_at' => null,
        'dnssec' => null,
        'dnssec_keys' => null,
        'domain' => null,
        'expiration_date' => null,
        'hard_quarantine_expiry_date' => null,
        'has_active_sectigo_zone' => 'boolean',
        'has_history' => 'boolean',
        'history' => null,
        'id' => 'int32',
        'internal_auth_code' => null,
        'is_abusive' => 'boolean',
        'is_client_hold_enabled' => null,
        'is_deleted' => 'boolean',
        'is_dnssec_enabled' => 'boolean',
        'is_hosted_whois' => 'boolean',
        'is_lockable' => 'boolean',
        'is_locked' => 'boolean',
        'is_parked' => 'boolean',
        'is_premium' => 'boolean',
        'is_private_whois_allowed' => 'boolean',
        'is_private_whois_enabled' => 'boolean',
        'is_sectigo_dns_enabled' => 'boolean',
        'is_spamexperts_enabled' => 'boolean',
        'last_changed' => null,
        'modify_owner_allowed' => 'boolean',
        'name_servers' => null,
        'ns_group' => null,
        'ns_template_id' => 'int32',
        'ns_template_name' => null,
        'nsgroup_id' => 'int32',
        'order_date' => null,
        'owner' => null,
        'owner_company_name' => null,
        'owner_handle' => null,
        'quarantine_expiration_date' => null,
        'registry_expiration_date' => null,
        'registry_statuses' => null,
        'renew' => 'int32',
        'renewal_date' => null,
        'reseller_handle' => null,
        'reseller_id' => 'int32',
        'restorable_until' => null,
        'scheduled_at' => null,
        'scheduled_from' => null,
        'soft_quarantine_expiry_date' => null,
        'status' => null,
        'tech_handle' => null,
        'trade_allowed' => 'boolean',
        'trade_auth_code_required' => null,
        'transfer_auth_code_required' => null,
        'transfer_cancel_supported' => 'boolean',
        'type' => null,
        'unit' => null,
        'use_domicile' => 'boolean',
        'verification_email_exp_date' => null,
        'verification_email_name' => null,
        'verification_email_status' => null,
        'verification_email_status_description' => null,
        'whois_privacy_data' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'abuse_details' => false,
		'active_date' => false,
		'additional_data' => false,
		'admin_handle' => false,
		'api_history' => false,
		'application_id' => false,
		'application_mode' => false,
		'application_mode_expiration_date' => false,
		'application_mode_title' => false,
		'application_notice_id' => false,
		'application_smd' => false,
		'auth_code' => false,
		'autorenew' => false,
		'billing_handle' => false,
		'can_renew' => false,
		'comments' => false,
		'comments_last_changed_at' => false,
		'creation_date' => false,
		'delete_status' => false,
		'deleted_at' => false,
		'dnssec' => false,
		'dnssec_keys' => false,
		'domain' => false,
		'expiration_date' => false,
		'hard_quarantine_expiry_date' => false,
		'has_active_sectigo_zone' => false,
		'has_history' => false,
		'history' => false,
		'id' => false,
		'internal_auth_code' => false,
		'is_abusive' => false,
		'is_client_hold_enabled' => false,
		'is_deleted' => false,
		'is_dnssec_enabled' => false,
		'is_hosted_whois' => false,
		'is_lockable' => false,
		'is_locked' => false,
		'is_parked' => false,
		'is_premium' => false,
		'is_private_whois_allowed' => false,
		'is_private_whois_enabled' => false,
		'is_sectigo_dns_enabled' => false,
		'is_spamexperts_enabled' => false,
		'last_changed' => false,
		'modify_owner_allowed' => false,
		'name_servers' => false,
		'ns_group' => false,
		'ns_template_id' => false,
		'ns_template_name' => false,
		'nsgroup_id' => false,
		'order_date' => false,
		'owner' => false,
		'owner_company_name' => false,
		'owner_handle' => false,
		'quarantine_expiration_date' => false,
		'registry_expiration_date' => false,
		'registry_statuses' => false,
		'renew' => false,
		'renewal_date' => false,
		'reseller_handle' => false,
		'reseller_id' => false,
		'restorable_until' => false,
		'scheduled_at' => false,
		'scheduled_from' => false,
		'soft_quarantine_expiry_date' => false,
		'status' => false,
		'tech_handle' => false,
		'trade_allowed' => false,
		'trade_auth_code_required' => false,
		'transfer_auth_code_required' => false,
		'transfer_cancel_supported' => false,
		'type' => false,
		'unit' => false,
		'use_domicile' => false,
		'verification_email_exp_date' => false,
		'verification_email_name' => false,
		'verification_email_status' => false,
		'verification_email_status_description' => false,
		'whois_privacy_data' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'abuse_details' => 'abuse_details',
        'active_date' => 'active_date',
        'additional_data' => 'additional_data',
        'admin_handle' => 'admin_handle',
        'api_history' => 'api_history',
        'application_id' => 'application_id',
        'application_mode' => 'application_mode',
        'application_mode_expiration_date' => 'application_mode_expiration_date',
        'application_mode_title' => 'application_mode_title',
        'application_notice_id' => 'application_notice_id',
        'application_smd' => 'application_smd',
        'auth_code' => 'auth_code',
        'autorenew' => 'autorenew',
        'billing_handle' => 'billing_handle',
        'can_renew' => 'can_renew',
        'comments' => 'comments',
        'comments_last_changed_at' => 'comments_last_changed_at',
        'creation_date' => 'creation_date',
        'delete_status' => 'delete_status',
        'deleted_at' => 'deleted_at',
        'dnssec' => 'dnssec',
        'dnssec_keys' => 'dnssec_keys',
        'domain' => 'domain',
        'expiration_date' => 'expiration_date',
        'hard_quarantine_expiry_date' => 'hard_quarantine_expiry_date',
        'has_active_sectigo_zone' => 'has_active_sectigo_zone',
        'has_history' => 'has_history',
        'history' => 'history',
        'id' => 'id',
        'internal_auth_code' => 'internal_auth_code',
        'is_abusive' => 'is_abusive',
        'is_client_hold_enabled' => 'is_client_hold_enabled',
        'is_deleted' => 'is_deleted',
        'is_dnssec_enabled' => 'is_dnssec_enabled',
        'is_hosted_whois' => 'is_hosted_whois',
        'is_lockable' => 'is_lockable',
        'is_locked' => 'is_locked',
        'is_parked' => 'is_parked',
        'is_premium' => 'is_premium',
        'is_private_whois_allowed' => 'is_private_whois_allowed',
        'is_private_whois_enabled' => 'is_private_whois_enabled',
        'is_sectigo_dns_enabled' => 'is_sectigo_dns_enabled',
        'is_spamexperts_enabled' => 'is_spamexperts_enabled',
        'last_changed' => 'last_changed',
        'modify_owner_allowed' => 'modify_owner_allowed',
        'name_servers' => 'name_servers',
        'ns_group' => 'ns_group',
        'ns_template_id' => 'ns_template_id',
        'ns_template_name' => 'ns_template_name',
        'nsgroup_id' => 'nsgroup_id',
        'order_date' => 'order_date',
        'owner' => 'owner',
        'owner_company_name' => 'owner_company_name',
        'owner_handle' => 'owner_handle',
        'quarantine_expiration_date' => 'quarantine_expiration_date',
        'registry_expiration_date' => 'registry_expiration_date',
        'registry_statuses' => 'registry_statuses',
        'renew' => 'renew',
        'renewal_date' => 'renewal_date',
        'reseller_handle' => 'reseller_handle',
        'reseller_id' => 'reseller_id',
        'restorable_until' => 'restorable_until',
        'scheduled_at' => 'scheduled_at',
        'scheduled_from' => 'scheduled_from',
        'soft_quarantine_expiry_date' => 'soft_quarantine_expiry_date',
        'status' => 'status',
        'tech_handle' => 'tech_handle',
        'trade_allowed' => 'trade_allowed',
        'trade_auth_code_required' => 'trade_auth_code_required',
        'transfer_auth_code_required' => 'transfer_auth_code_required',
        'transfer_cancel_supported' => 'transfer_cancel_supported',
        'type' => 'type',
        'unit' => 'unit',
        'use_domicile' => 'use_domicile',
        'verification_email_exp_date' => 'verification_email_exp_date',
        'verification_email_name' => 'verification_email_name',
        'verification_email_status' => 'verification_email_status',
        'verification_email_status_description' => 'verification_email_status_description',
        'whois_privacy_data' => 'whois_privacy_data'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'abuse_details' => 'setAbuseDetails',
        'active_date' => 'setActiveDate',
        'additional_data' => 'setAdditionalData',
        'admin_handle' => 'setAdminHandle',
        'api_history' => 'setApiHistory',
        'application_id' => 'setApplicationId',
        'application_mode' => 'setApplicationMode',
        'application_mode_expiration_date' => 'setApplicationModeExpirationDate',
        'application_mode_title' => 'setApplicationModeTitle',
        'application_notice_id' => 'setApplicationNoticeId',
        'application_smd' => 'setApplicationSmd',
        'auth_code' => 'setAuthCode',
        'autorenew' => 'setAutorenew',
        'billing_handle' => 'setBillingHandle',
        'can_renew' => 'setCanRenew',
        'comments' => 'setComments',
        'comments_last_changed_at' => 'setCommentsLastChangedAt',
        'creation_date' => 'setCreationDate',
        'delete_status' => 'setDeleteStatus',
        'deleted_at' => 'setDeletedAt',
        'dnssec' => 'setDnssec',
        'dnssec_keys' => 'setDnssecKeys',
        'domain' => 'setDomain',
        'expiration_date' => 'setExpirationDate',
        'hard_quarantine_expiry_date' => 'setHardQuarantineExpiryDate',
        'has_active_sectigo_zone' => 'setHasActiveSectigoZone',
        'has_history' => 'setHasHistory',
        'history' => 'setHistory',
        'id' => 'setId',
        'internal_auth_code' => 'setInternalAuthCode',
        'is_abusive' => 'setIsAbusive',
        'is_client_hold_enabled' => 'setIsClientHoldEnabled',
        'is_deleted' => 'setIsDeleted',
        'is_dnssec_enabled' => 'setIsDnssecEnabled',
        'is_hosted_whois' => 'setIsHostedWhois',
        'is_lockable' => 'setIsLockable',
        'is_locked' => 'setIsLocked',
        'is_parked' => 'setIsParked',
        'is_premium' => 'setIsPremium',
        'is_private_whois_allowed' => 'setIsPrivateWhoisAllowed',
        'is_private_whois_enabled' => 'setIsPrivateWhoisEnabled',
        'is_sectigo_dns_enabled' => 'setIsSectigoDnsEnabled',
        'is_spamexperts_enabled' => 'setIsSpamexpertsEnabled',
        'last_changed' => 'setLastChanged',
        'modify_owner_allowed' => 'setModifyOwnerAllowed',
        'name_servers' => 'setNameServers',
        'ns_group' => 'setNsGroup',
        'ns_template_id' => 'setNsTemplateId',
        'ns_template_name' => 'setNsTemplateName',
        'nsgroup_id' => 'setNsgroupId',
        'order_date' => 'setOrderDate',
        'owner' => 'setOwner',
        'owner_company_name' => 'setOwnerCompanyName',
        'owner_handle' => 'setOwnerHandle',
        'quarantine_expiration_date' => 'setQuarantineExpirationDate',
        'registry_expiration_date' => 'setRegistryExpirationDate',
        'registry_statuses' => 'setRegistryStatuses',
        'renew' => 'setRenew',
        'renewal_date' => 'setRenewalDate',
        'reseller_handle' => 'setResellerHandle',
        'reseller_id' => 'setResellerId',
        'restorable_until' => 'setRestorableUntil',
        'scheduled_at' => 'setScheduledAt',
        'scheduled_from' => 'setScheduledFrom',
        'soft_quarantine_expiry_date' => 'setSoftQuarantineExpiryDate',
        'status' => 'setStatus',
        'tech_handle' => 'setTechHandle',
        'trade_allowed' => 'setTradeAllowed',
        'trade_auth_code_required' => 'setTradeAuthCodeRequired',
        'transfer_auth_code_required' => 'setTransferAuthCodeRequired',
        'transfer_cancel_supported' => 'setTransferCancelSupported',
        'type' => 'setType',
        'unit' => 'setUnit',
        'use_domicile' => 'setUseDomicile',
        'verification_email_exp_date' => 'setVerificationEmailExpDate',
        'verification_email_name' => 'setVerificationEmailName',
        'verification_email_status' => 'setVerificationEmailStatus',
        'verification_email_status_description' => 'setVerificationEmailStatusDescription',
        'whois_privacy_data' => 'setWhoisPrivacyData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'abuse_details' => 'getAbuseDetails',
        'active_date' => 'getActiveDate',
        'additional_data' => 'getAdditionalData',
        'admin_handle' => 'getAdminHandle',
        'api_history' => 'getApiHistory',
        'application_id' => 'getApplicationId',
        'application_mode' => 'getApplicationMode',
        'application_mode_expiration_date' => 'getApplicationModeExpirationDate',
        'application_mode_title' => 'getApplicationModeTitle',
        'application_notice_id' => 'getApplicationNoticeId',
        'application_smd' => 'getApplicationSmd',
        'auth_code' => 'getAuthCode',
        'autorenew' => 'getAutorenew',
        'billing_handle' => 'getBillingHandle',
        'can_renew' => 'getCanRenew',
        'comments' => 'getComments',
        'comments_last_changed_at' => 'getCommentsLastChangedAt',
        'creation_date' => 'getCreationDate',
        'delete_status' => 'getDeleteStatus',
        'deleted_at' => 'getDeletedAt',
        'dnssec' => 'getDnssec',
        'dnssec_keys' => 'getDnssecKeys',
        'domain' => 'getDomain',
        'expiration_date' => 'getExpirationDate',
        'hard_quarantine_expiry_date' => 'getHardQuarantineExpiryDate',
        'has_active_sectigo_zone' => 'getHasActiveSectigoZone',
        'has_history' => 'getHasHistory',
        'history' => 'getHistory',
        'id' => 'getId',
        'internal_auth_code' => 'getInternalAuthCode',
        'is_abusive' => 'getIsAbusive',
        'is_client_hold_enabled' => 'getIsClientHoldEnabled',
        'is_deleted' => 'getIsDeleted',
        'is_dnssec_enabled' => 'getIsDnssecEnabled',
        'is_hosted_whois' => 'getIsHostedWhois',
        'is_lockable' => 'getIsLockable',
        'is_locked' => 'getIsLocked',
        'is_parked' => 'getIsParked',
        'is_premium' => 'getIsPremium',
        'is_private_whois_allowed' => 'getIsPrivateWhoisAllowed',
        'is_private_whois_enabled' => 'getIsPrivateWhoisEnabled',
        'is_sectigo_dns_enabled' => 'getIsSectigoDnsEnabled',
        'is_spamexperts_enabled' => 'getIsSpamexpertsEnabled',
        'last_changed' => 'getLastChanged',
        'modify_owner_allowed' => 'getModifyOwnerAllowed',
        'name_servers' => 'getNameServers',
        'ns_group' => 'getNsGroup',
        'ns_template_id' => 'getNsTemplateId',
        'ns_template_name' => 'getNsTemplateName',
        'nsgroup_id' => 'getNsgroupId',
        'order_date' => 'getOrderDate',
        'owner' => 'getOwner',
        'owner_company_name' => 'getOwnerCompanyName',
        'owner_handle' => 'getOwnerHandle',
        'quarantine_expiration_date' => 'getQuarantineExpirationDate',
        'registry_expiration_date' => 'getRegistryExpirationDate',
        'registry_statuses' => 'getRegistryStatuses',
        'renew' => 'getRenew',
        'renewal_date' => 'getRenewalDate',
        'reseller_handle' => 'getResellerHandle',
        'reseller_id' => 'getResellerId',
        'restorable_until' => 'getRestorableUntil',
        'scheduled_at' => 'getScheduledAt',
        'scheduled_from' => 'getScheduledFrom',
        'soft_quarantine_expiry_date' => 'getSoftQuarantineExpiryDate',
        'status' => 'getStatus',
        'tech_handle' => 'getTechHandle',
        'trade_allowed' => 'getTradeAllowed',
        'trade_auth_code_required' => 'getTradeAuthCodeRequired',
        'transfer_auth_code_required' => 'getTransferAuthCodeRequired',
        'transfer_cancel_supported' => 'getTransferCancelSupported',
        'type' => 'getType',
        'unit' => 'getUnit',
        'use_domicile' => 'getUseDomicile',
        'verification_email_exp_date' => 'getVerificationEmailExpDate',
        'verification_email_name' => 'getVerificationEmailName',
        'verification_email_status' => 'getVerificationEmailStatus',
        'verification_email_status_description' => 'getVerificationEmailStatusDescription',
        'whois_privacy_data' => 'getWhoisPrivacyData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('abuse_details', $data ?? [], null);
        $this->setIfExists('active_date', $data ?? [], null);
        $this->setIfExists('additional_data', $data ?? [], null);
        $this->setIfExists('admin_handle', $data ?? [], null);
        $this->setIfExists('api_history', $data ?? [], null);
        $this->setIfExists('application_id', $data ?? [], null);
        $this->setIfExists('application_mode', $data ?? [], null);
        $this->setIfExists('application_mode_expiration_date', $data ?? [], null);
        $this->setIfExists('application_mode_title', $data ?? [], null);
        $this->setIfExists('application_notice_id', $data ?? [], null);
        $this->setIfExists('application_smd', $data ?? [], null);
        $this->setIfExists('auth_code', $data ?? [], null);
        $this->setIfExists('autorenew', $data ?? [], null);
        $this->setIfExists('billing_handle', $data ?? [], null);
        $this->setIfExists('can_renew', $data ?? [], null);
        $this->setIfExists('comments', $data ?? [], null);
        $this->setIfExists('comments_last_changed_at', $data ?? [], null);
        $this->setIfExists('creation_date', $data ?? [], null);
        $this->setIfExists('delete_status', $data ?? [], null);
        $this->setIfExists('deleted_at', $data ?? [], null);
        $this->setIfExists('dnssec', $data ?? [], null);
        $this->setIfExists('dnssec_keys', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('expiration_date', $data ?? [], null);
        $this->setIfExists('hard_quarantine_expiry_date', $data ?? [], null);
        $this->setIfExists('has_active_sectigo_zone', $data ?? [], null);
        $this->setIfExists('has_history', $data ?? [], null);
        $this->setIfExists('history', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('internal_auth_code', $data ?? [], null);
        $this->setIfExists('is_abusive', $data ?? [], null);
        $this->setIfExists('is_client_hold_enabled', $data ?? [], null);
        $this->setIfExists('is_deleted', $data ?? [], null);
        $this->setIfExists('is_dnssec_enabled', $data ?? [], null);
        $this->setIfExists('is_hosted_whois', $data ?? [], null);
        $this->setIfExists('is_lockable', $data ?? [], null);
        $this->setIfExists('is_locked', $data ?? [], null);
        $this->setIfExists('is_parked', $data ?? [], null);
        $this->setIfExists('is_premium', $data ?? [], null);
        $this->setIfExists('is_private_whois_allowed', $data ?? [], null);
        $this->setIfExists('is_private_whois_enabled', $data ?? [], null);
        $this->setIfExists('is_sectigo_dns_enabled', $data ?? [], null);
        $this->setIfExists('is_spamexperts_enabled', $data ?? [], null);
        $this->setIfExists('last_changed', $data ?? [], null);
        $this->setIfExists('modify_owner_allowed', $data ?? [], null);
        $this->setIfExists('name_servers', $data ?? [], null);
        $this->setIfExists('ns_group', $data ?? [], null);
        $this->setIfExists('ns_template_id', $data ?? [], null);
        $this->setIfExists('ns_template_name', $data ?? [], null);
        $this->setIfExists('nsgroup_id', $data ?? [], null);
        $this->setIfExists('order_date', $data ?? [], null);
        $this->setIfExists('owner', $data ?? [], null);
        $this->setIfExists('owner_company_name', $data ?? [], null);
        $this->setIfExists('owner_handle', $data ?? [], null);
        $this->setIfExists('quarantine_expiration_date', $data ?? [], null);
        $this->setIfExists('registry_expiration_date', $data ?? [], null);
        $this->setIfExists('registry_statuses', $data ?? [], null);
        $this->setIfExists('renew', $data ?? [], null);
        $this->setIfExists('renewal_date', $data ?? [], null);
        $this->setIfExists('reseller_handle', $data ?? [], null);
        $this->setIfExists('reseller_id', $data ?? [], null);
        $this->setIfExists('restorable_until', $data ?? [], null);
        $this->setIfExists('scheduled_at', $data ?? [], null);
        $this->setIfExists('scheduled_from', $data ?? [], null);
        $this->setIfExists('soft_quarantine_expiry_date', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('tech_handle', $data ?? [], null);
        $this->setIfExists('trade_allowed', $data ?? [], null);
        $this->setIfExists('trade_auth_code_required', $data ?? [], null);
        $this->setIfExists('transfer_auth_code_required', $data ?? [], null);
        $this->setIfExists('transfer_cancel_supported', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('unit', $data ?? [], null);
        $this->setIfExists('use_domicile', $data ?? [], null);
        $this->setIfExists('verification_email_exp_date', $data ?? [], null);
        $this->setIfExists('verification_email_name', $data ?? [], null);
        $this->setIfExists('verification_email_status', $data ?? [], null);
        $this->setIfExists('verification_email_status_description', $data ?? [], null);
        $this->setIfExists('whois_privacy_data', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets abuse_details
     *
     * @return \Savvii\OpenproviderRest\Model\DomainAbuseDetails|null
     */
    public function getAbuseDetails()
    {
        return $this->container['abuse_details'];
    }

    /**
     * Sets abuse_details
     *
     * @param \Savvii\OpenproviderRest\Model\DomainAbuseDetails|null $abuse_details abuse_details
     *
     * @return self
     */
    public function setAbuseDetails($abuse_details)
    {
        if (is_null($abuse_details)) {
            throw new \InvalidArgumentException('non-nullable abuse_details cannot be null');
        }
        $this->container['abuse_details'] = $abuse_details;

        return $this;
    }

    /**
     * Gets active_date
     *
     * @return string|null
     */
    public function getActiveDate()
    {
        return $this->container['active_date'];
    }

    /**
     * Sets active_date
     *
     * @param string|null $active_date active_date
     *
     * @return self
     */
    public function setActiveDate($active_date)
    {
        if (is_null($active_date)) {
            throw new \InvalidArgumentException('non-nullable active_date cannot be null');
        }
        $this->container['active_date'] = $active_date;

        return $this;
    }

    /**
     * Gets additional_data
     *
     * @return \Savvii\OpenproviderRest\Model\DomainAdditionalData|null
     */
    public function getAdditionalData()
    {
        return $this->container['additional_data'];
    }

    /**
     * Sets additional_data
     *
     * @param \Savvii\OpenproviderRest\Model\DomainAdditionalData|null $additional_data additional_data
     *
     * @return self
     */
    public function setAdditionalData($additional_data)
    {
        if (is_null($additional_data)) {
            throw new \InvalidArgumentException('non-nullable additional_data cannot be null');
        }
        $this->container['additional_data'] = $additional_data;

        return $this;
    }

    /**
     * Gets admin_handle
     *
     * @return string|null
     */
    public function getAdminHandle()
    {
        return $this->container['admin_handle'];
    }

    /**
     * Sets admin_handle
     *
     * @param string|null $admin_handle admin_handle
     *
     * @return self
     */
    public function setAdminHandle($admin_handle)
    {
        if (is_null($admin_handle)) {
            throw new \InvalidArgumentException('non-nullable admin_handle cannot be null');
        }
        $this->container['admin_handle'] = $admin_handle;

        return $this;
    }

    /**
     * Gets api_history
     *
     * @return \Savvii\OpenproviderRest\Model\DomainApiHistory[]|null
     */
    public function getApiHistory()
    {
        return $this->container['api_history'];
    }

    /**
     * Sets api_history
     *
     * @param \Savvii\OpenproviderRest\Model\DomainApiHistory[]|null $api_history api_history
     *
     * @return self
     */
    public function setApiHistory($api_history)
    {
        if (is_null($api_history)) {
            throw new \InvalidArgumentException('non-nullable api_history cannot be null');
        }
        $this->container['api_history'] = $api_history;

        return $this;
    }

    /**
     * Gets application_id
     *
     * @return string|null
     */
    public function getApplicationId()
    {
        return $this->container['application_id'];
    }

    /**
     * Sets application_id
     *
     * @param string|null $application_id application_id
     *
     * @return self
     */
    public function setApplicationId($application_id)
    {
        if (is_null($application_id)) {
            throw new \InvalidArgumentException('non-nullable application_id cannot be null');
        }
        $this->container['application_id'] = $application_id;

        return $this;
    }

    /**
     * Gets application_mode
     *
     * @return string|null
     */
    public function getApplicationMode()
    {
        return $this->container['application_mode'];
    }

    /**
     * Sets application_mode
     *
     * @param string|null $application_mode When new gTLD is started it gets through several phases before it becomes available for registration to everybody (General availability or GA). There are several phases before GA when it is still possible to apply for a domain, but with some restrictions.
     *
     * @return self
     */
    public function setApplicationMode($application_mode)
    {
        if (is_null($application_mode)) {
            throw new \InvalidArgumentException('non-nullable application_mode cannot be null');
        }
        $this->container['application_mode'] = $application_mode;

        return $this;
    }

    /**
     * Gets application_mode_expiration_date
     *
     * @return string|null
     */
    public function getApplicationModeExpirationDate()
    {
        return $this->container['application_mode_expiration_date'];
    }

    /**
     * Sets application_mode_expiration_date
     *
     * @param string|null $application_mode_expiration_date application_mode_expiration_date
     *
     * @return self
     */
    public function setApplicationModeExpirationDate($application_mode_expiration_date)
    {
        if (is_null($application_mode_expiration_date)) {
            throw new \InvalidArgumentException('non-nullable application_mode_expiration_date cannot be null');
        }
        $this->container['application_mode_expiration_date'] = $application_mode_expiration_date;

        return $this;
    }

    /**
     * Gets application_mode_title
     *
     * @return string|null
     */
    public function getApplicationModeTitle()
    {
        return $this->container['application_mode_title'];
    }

    /**
     * Sets application_mode_title
     *
     * @param string|null $application_mode_title application_mode_title
     *
     * @return self
     */
    public function setApplicationModeTitle($application_mode_title)
    {
        if (is_null($application_mode_title)) {
            throw new \InvalidArgumentException('non-nullable application_mode_title cannot be null');
        }
        $this->container['application_mode_title'] = $application_mode_title;

        return $this;
    }

    /**
     * Gets application_notice_id
     *
     * @return string|null
     */
    public function getApplicationNoticeId()
    {
        return $this->container['application_notice_id'];
    }

    /**
     * Sets application_notice_id
     *
     * @param string|null $application_notice_id application_notice_id
     *
     * @return self
     */
    public function setApplicationNoticeId($application_notice_id)
    {
        if (is_null($application_notice_id)) {
            throw new \InvalidArgumentException('non-nullable application_notice_id cannot be null');
        }
        $this->container['application_notice_id'] = $application_notice_id;

        return $this;
    }

    /**
     * Gets application_smd
     *
     * @return string|null
     */
    public function getApplicationSmd()
    {
        return $this->container['application_smd'];
    }

    /**
     * Sets application_smd
     *
     * @param string|null $application_smd application_smd
     *
     * @return self
     */
    public function setApplicationSmd($application_smd)
    {
        if (is_null($application_smd)) {
            throw new \InvalidArgumentException('non-nullable application_smd cannot be null');
        }
        $this->container['application_smd'] = $application_smd;

        return $this;
    }

    /**
     * Gets auth_code
     *
     * @return string|null
     */
    public function getAuthCode()
    {
        return $this->container['auth_code'];
    }

    /**
     * Sets auth_code
     *
     * @param string|null $auth_code auth_code
     *
     * @return self
     */
    public function setAuthCode($auth_code)
    {
        if (is_null($auth_code)) {
            throw new \InvalidArgumentException('non-nullable auth_code cannot be null');
        }
        $this->container['auth_code'] = $auth_code;

        return $this;
    }

    /**
     * Gets autorenew
     *
     * @return string|null
     */
    public function getAutorenew()
    {
        return $this->container['autorenew'];
    }

    /**
     * Sets autorenew
     *
     * @param string|null $autorenew autorenew
     *
     * @return self
     */
    public function setAutorenew($autorenew)
    {
        if (is_null($autorenew)) {
            throw new \InvalidArgumentException('non-nullable autorenew cannot be null');
        }
        $this->container['autorenew'] = $autorenew;

        return $this;
    }

    /**
     * Gets billing_handle
     *
     * @return string|null
     */
    public function getBillingHandle()
    {
        return $this->container['billing_handle'];
    }

    /**
     * Sets billing_handle
     *
     * @param string|null $billing_handle billing_handle
     *
     * @return self
     */
    public function setBillingHandle($billing_handle)
    {
        if (is_null($billing_handle)) {
            throw new \InvalidArgumentException('non-nullable billing_handle cannot be null');
        }
        $this->container['billing_handle'] = $billing_handle;

        return $this;
    }

    /**
     * Gets can_renew
     *
     * @return bool|null
     */
    public function getCanRenew()
    {
        return $this->container['can_renew'];
    }

    /**
     * Sets can_renew
     *
     * @param bool|null $can_renew can_renew
     *
     * @return self
     */
    public function setCanRenew($can_renew)
    {
        if (is_null($can_renew)) {
            throw new \InvalidArgumentException('non-nullable can_renew cannot be null');
        }
        $this->container['can_renew'] = $can_renew;

        return $this;
    }

    /**
     * Gets comments
     *
     * @return string|null
     */
    public function getComments()
    {
        return $this->container['comments'];
    }

    /**
     * Sets comments
     *
     * @param string|null $comments comments
     *
     * @return self
     */
    public function setComments($comments)
    {
        if (is_null($comments)) {
            throw new \InvalidArgumentException('non-nullable comments cannot be null');
        }
        $this->container['comments'] = $comments;

        return $this;
    }

    /**
     * Gets comments_last_changed_at
     *
     * @return string|null
     */
    public function getCommentsLastChangedAt()
    {
        return $this->container['comments_last_changed_at'];
    }

    /**
     * Sets comments_last_changed_at
     *
     * @param string|null $comments_last_changed_at comments_last_changed_at
     *
     * @return self
     */
    public function setCommentsLastChangedAt($comments_last_changed_at)
    {
        if (is_null($comments_last_changed_at)) {
            throw new \InvalidArgumentException('non-nullable comments_last_changed_at cannot be null');
        }
        $this->container['comments_last_changed_at'] = $comments_last_changed_at;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return string|null
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param string|null $creation_date creation_date
     *
     * @return self
     */
    public function setCreationDate($creation_date)
    {
        if (is_null($creation_date)) {
            throw new \InvalidArgumentException('non-nullable creation_date cannot be null');
        }
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets delete_status
     *
     * @return string|null
     */
    public function getDeleteStatus()
    {
        return $this->container['delete_status'];
    }

    /**
     * Sets delete_status
     *
     * @param string|null $delete_status delete_status
     *
     * @return self
     */
    public function setDeleteStatus($delete_status)
    {
        if (is_null($delete_status)) {
            throw new \InvalidArgumentException('non-nullable delete_status cannot be null');
        }
        $this->container['delete_status'] = $delete_status;

        return $this;
    }

    /**
     * Gets deleted_at
     *
     * @return string|null
     */
    public function getDeletedAt()
    {
        return $this->container['deleted_at'];
    }

    /**
     * Sets deleted_at
     *
     * @param string|null $deleted_at deleted_at
     *
     * @return self
     */
    public function setDeletedAt($deleted_at)
    {
        if (is_null($deleted_at)) {
            throw new \InvalidArgumentException('non-nullable deleted_at cannot be null');
        }
        $this->container['deleted_at'] = $deleted_at;

        return $this;
    }

    /**
     * Gets dnssec
     *
     * @return string|null
     */
    public function getDnssec()
    {
        return $this->container['dnssec'];
    }

    /**
     * Sets dnssec
     *
     * @param string|null $dnssec Indicates, if DNSSEC is enabled. Possible values: signedDelegation, unsigned.
     *
     * @return self
     */
    public function setDnssec($dnssec)
    {
        if (is_null($dnssec)) {
            throw new \InvalidArgumentException('non-nullable dnssec cannot be null');
        }
        $this->container['dnssec'] = $dnssec;

        return $this;
    }

    /**
     * Gets dnssec_keys
     *
     * @return \Savvii\OpenproviderRest\Model\DomainDnssecKey[]|null
     */
    public function getDnssecKeys()
    {
        return $this->container['dnssec_keys'];
    }

    /**
     * Sets dnssec_keys
     *
     * @param \Savvii\OpenproviderRest\Model\DomainDnssecKey[]|null $dnssec_keys dnssec_keys
     *
     * @return self
     */
    public function setDnssecKeys($dnssec_keys)
    {
        if (is_null($dnssec_keys)) {
            throw new \InvalidArgumentException('non-nullable dnssec_keys cannot be null');
        }
        $this->container['dnssec_keys'] = $dnssec_keys;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return \Savvii\OpenproviderRest\Model\DomainDomain|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param \Savvii\OpenproviderRest\Model\DomainDomain|null $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets expiration_date
     *
     * @return string|null
     */
    public function getExpirationDate()
    {
        return $this->container['expiration_date'];
    }

    /**
     * Sets expiration_date
     *
     * @param string|null $expiration_date expiration_date
     *
     * @return self
     */
    public function setExpirationDate($expiration_date)
    {
        if (is_null($expiration_date)) {
            throw new \InvalidArgumentException('non-nullable expiration_date cannot be null');
        }
        $this->container['expiration_date'] = $expiration_date;

        return $this;
    }

    /**
     * Gets hard_quarantine_expiry_date
     *
     * @return string|null
     */
    public function getHardQuarantineExpiryDate()
    {
        return $this->container['hard_quarantine_expiry_date'];
    }

    /**
     * Sets hard_quarantine_expiry_date
     *
     * @param string|null $hard_quarantine_expiry_date hard_quarantine_expiry_date
     *
     * @return self
     */
    public function setHardQuarantineExpiryDate($hard_quarantine_expiry_date)
    {
        if (is_null($hard_quarantine_expiry_date)) {
            throw new \InvalidArgumentException('non-nullable hard_quarantine_expiry_date cannot be null');
        }
        $this->container['hard_quarantine_expiry_date'] = $hard_quarantine_expiry_date;

        return $this;
    }

    /**
     * Gets has_active_sectigo_zone
     *
     * @return bool|null
     */
    public function getHasActiveSectigoZone()
    {
        return $this->container['has_active_sectigo_zone'];
    }

    /**
     * Sets has_active_sectigo_zone
     *
     * @param bool|null $has_active_sectigo_zone has_active_sectigo_zone
     *
     * @return self
     */
    public function setHasActiveSectigoZone($has_active_sectigo_zone)
    {
        if (is_null($has_active_sectigo_zone)) {
            throw new \InvalidArgumentException('non-nullable has_active_sectigo_zone cannot be null');
        }
        $this->container['has_active_sectigo_zone'] = $has_active_sectigo_zone;

        return $this;
    }

    /**
     * Gets has_history
     *
     * @return bool|null
     */
    public function getHasHistory()
    {
        return $this->container['has_history'];
    }

    /**
     * Sets has_history
     *
     * @param bool|null $has_history has_history
     *
     * @return self
     */
    public function setHasHistory($has_history)
    {
        if (is_null($has_history)) {
            throw new \InvalidArgumentException('non-nullable has_history cannot be null');
        }
        $this->container['has_history'] = $has_history;

        return $this;
    }

    /**
     * Gets history
     *
     * @return \Savvii\OpenproviderRest\Model\DomainHistory[]|null
     */
    public function getHistory()
    {
        return $this->container['history'];
    }

    /**
     * Sets history
     *
     * @param \Savvii\OpenproviderRest\Model\DomainHistory[]|null $history history
     *
     * @return self
     */
    public function setHistory($history)
    {
        if (is_null($history)) {
            throw new \InvalidArgumentException('non-nullable history cannot be null');
        }
        $this->container['history'] = $history;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets internal_auth_code
     *
     * @return string|null
     */
    public function getInternalAuthCode()
    {
        return $this->container['internal_auth_code'];
    }

    /**
     * Sets internal_auth_code
     *
     * @param string|null $internal_auth_code internal_auth_code
     *
     * @return self
     */
    public function setInternalAuthCode($internal_auth_code)
    {
        if (is_null($internal_auth_code)) {
            throw new \InvalidArgumentException('non-nullable internal_auth_code cannot be null');
        }
        $this->container['internal_auth_code'] = $internal_auth_code;

        return $this;
    }

    /**
     * Gets is_abusive
     *
     * @return bool|null
     */
    public function getIsAbusive()
    {
        return $this->container['is_abusive'];
    }

    /**
     * Sets is_abusive
     *
     * @param bool|null $is_abusive is_abusive
     *
     * @return self
     */
    public function setIsAbusive($is_abusive)
    {
        if (is_null($is_abusive)) {
            throw new \InvalidArgumentException('non-nullable is_abusive cannot be null');
        }
        $this->container['is_abusive'] = $is_abusive;

        return $this;
    }

    /**
     * Gets is_client_hold_enabled
     *
     * @return string|null
     */
    public function getIsClientHoldEnabled()
    {
        return $this->container['is_client_hold_enabled'];
    }

    /**
     * Sets is_client_hold_enabled
     *
     * @param string|null $is_client_hold_enabled is_client_hold_enabled
     *
     * @return self
     */
    public function setIsClientHoldEnabled($is_client_hold_enabled)
    {
        if (is_null($is_client_hold_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_client_hold_enabled cannot be null');
        }
        $this->container['is_client_hold_enabled'] = $is_client_hold_enabled;

        return $this;
    }

    /**
     * Gets is_deleted
     *
     * @return bool|null
     */
    public function getIsDeleted()
    {
        return $this->container['is_deleted'];
    }

    /**
     * Sets is_deleted
     *
     * @param bool|null $is_deleted is_deleted
     *
     * @return self
     */
    public function setIsDeleted($is_deleted)
    {
        if (is_null($is_deleted)) {
            throw new \InvalidArgumentException('non-nullable is_deleted cannot be null');
        }
        $this->container['is_deleted'] = $is_deleted;

        return $this;
    }

    /**
     * Gets is_dnssec_enabled
     *
     * @return bool|null
     */
    public function getIsDnssecEnabled()
    {
        return $this->container['is_dnssec_enabled'];
    }

    /**
     * Sets is_dnssec_enabled
     *
     * @param bool|null $is_dnssec_enabled is_dnssec_enabled
     *
     * @return self
     */
    public function setIsDnssecEnabled($is_dnssec_enabled)
    {
        if (is_null($is_dnssec_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_dnssec_enabled cannot be null');
        }
        $this->container['is_dnssec_enabled'] = $is_dnssec_enabled;

        return $this;
    }

    /**
     * Gets is_hosted_whois
     *
     * @return bool|null
     */
    public function getIsHostedWhois()
    {
        return $this->container['is_hosted_whois'];
    }

    /**
     * Sets is_hosted_whois
     *
     * @param bool|null $is_hosted_whois is_hosted_whois
     *
     * @return self
     */
    public function setIsHostedWhois($is_hosted_whois)
    {
        if (is_null($is_hosted_whois)) {
            throw new \InvalidArgumentException('non-nullable is_hosted_whois cannot be null');
        }
        $this->container['is_hosted_whois'] = $is_hosted_whois;

        return $this;
    }

    /**
     * Gets is_lockable
     *
     * @return bool|null
     */
    public function getIsLockable()
    {
        return $this->container['is_lockable'];
    }

    /**
     * Sets is_lockable
     *
     * @param bool|null $is_lockable is_lockable
     *
     * @return self
     */
    public function setIsLockable($is_lockable)
    {
        if (is_null($is_lockable)) {
            throw new \InvalidArgumentException('non-nullable is_lockable cannot be null');
        }
        $this->container['is_lockable'] = $is_lockable;

        return $this;
    }

    /**
     * Gets is_locked
     *
     * @return bool|null
     */
    public function getIsLocked()
    {
        return $this->container['is_locked'];
    }

    /**
     * Sets is_locked
     *
     * @param bool|null $is_locked is_locked
     *
     * @return self
     */
    public function setIsLocked($is_locked)
    {
        if (is_null($is_locked)) {
            throw new \InvalidArgumentException('non-nullable is_locked cannot be null');
        }
        $this->container['is_locked'] = $is_locked;

        return $this;
    }

    /**
     * Gets is_parked
     *
     * @return bool|null
     */
    public function getIsParked()
    {
        return $this->container['is_parked'];
    }

    /**
     * Sets is_parked
     *
     * @param bool|null $is_parked is_parked
     *
     * @return self
     */
    public function setIsParked($is_parked)
    {
        if (is_null($is_parked)) {
            throw new \InvalidArgumentException('non-nullable is_parked cannot be null');
        }
        $this->container['is_parked'] = $is_parked;

        return $this;
    }

    /**
     * Gets is_premium
     *
     * @return bool|null
     */
    public function getIsPremium()
    {
        return $this->container['is_premium'];
    }

    /**
     * Sets is_premium
     *
     * @param bool|null $is_premium is_premium
     *
     * @return self
     */
    public function setIsPremium($is_premium)
    {
        if (is_null($is_premium)) {
            throw new \InvalidArgumentException('non-nullable is_premium cannot be null');
        }
        $this->container['is_premium'] = $is_premium;

        return $this;
    }

    /**
     * Gets is_private_whois_allowed
     *
     * @return bool|null
     */
    public function getIsPrivateWhoisAllowed()
    {
        return $this->container['is_private_whois_allowed'];
    }

    /**
     * Sets is_private_whois_allowed
     *
     * @param bool|null $is_private_whois_allowed is_private_whois_allowed
     *
     * @return self
     */
    public function setIsPrivateWhoisAllowed($is_private_whois_allowed)
    {
        if (is_null($is_private_whois_allowed)) {
            throw new \InvalidArgumentException('non-nullable is_private_whois_allowed cannot be null');
        }
        $this->container['is_private_whois_allowed'] = $is_private_whois_allowed;

        return $this;
    }

    /**
     * Gets is_private_whois_enabled
     *
     * @return bool|null
     */
    public function getIsPrivateWhoisEnabled()
    {
        return $this->container['is_private_whois_enabled'];
    }

    /**
     * Sets is_private_whois_enabled
     *
     * @param bool|null $is_private_whois_enabled is_private_whois_enabled
     *
     * @return self
     */
    public function setIsPrivateWhoisEnabled($is_private_whois_enabled)
    {
        if (is_null($is_private_whois_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_private_whois_enabled cannot be null');
        }
        $this->container['is_private_whois_enabled'] = $is_private_whois_enabled;

        return $this;
    }

    /**
     * Gets is_sectigo_dns_enabled
     *
     * @return bool|null
     */
    public function getIsSectigoDnsEnabled()
    {
        return $this->container['is_sectigo_dns_enabled'];
    }

    /**
     * Sets is_sectigo_dns_enabled
     *
     * @param bool|null $is_sectigo_dns_enabled is_sectigo_dns_enabled
     *
     * @return self
     */
    public function setIsSectigoDnsEnabled($is_sectigo_dns_enabled)
    {
        if (is_null($is_sectigo_dns_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_sectigo_dns_enabled cannot be null');
        }
        $this->container['is_sectigo_dns_enabled'] = $is_sectigo_dns_enabled;

        return $this;
    }

    /**
     * Gets is_spamexperts_enabled
     *
     * @return bool|null
     */
    public function getIsSpamexpertsEnabled()
    {
        return $this->container['is_spamexperts_enabled'];
    }

    /**
     * Sets is_spamexperts_enabled
     *
     * @param bool|null $is_spamexperts_enabled is_spamexperts_enabled
     *
     * @return self
     */
    public function setIsSpamexpertsEnabled($is_spamexperts_enabled)
    {
        if (is_null($is_spamexperts_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_spamexperts_enabled cannot be null');
        }
        $this->container['is_spamexperts_enabled'] = $is_spamexperts_enabled;

        return $this;
    }

    /**
     * Gets last_changed
     *
     * @return string|null
     */
    public function getLastChanged()
    {
        return $this->container['last_changed'];
    }

    /**
     * Sets last_changed
     *
     * @param string|null $last_changed last_changed
     *
     * @return self
     */
    public function setLastChanged($last_changed)
    {
        if (is_null($last_changed)) {
            throw new \InvalidArgumentException('non-nullable last_changed cannot be null');
        }
        $this->container['last_changed'] = $last_changed;

        return $this;
    }

    /**
     * Gets modify_owner_allowed
     *
     * @return bool|null
     */
    public function getModifyOwnerAllowed()
    {
        return $this->container['modify_owner_allowed'];
    }

    /**
     * Sets modify_owner_allowed
     *
     * @param bool|null $modify_owner_allowed modify_owner_allowed
     *
     * @return self
     */
    public function setModifyOwnerAllowed($modify_owner_allowed)
    {
        if (is_null($modify_owner_allowed)) {
            throw new \InvalidArgumentException('non-nullable modify_owner_allowed cannot be null');
        }
        $this->container['modify_owner_allowed'] = $modify_owner_allowed;

        return $this;
    }

    /**
     * Gets name_servers
     *
     * @return \Savvii\OpenproviderRest\Model\DomainNameserver[]|null
     */
    public function getNameServers()
    {
        return $this->container['name_servers'];
    }

    /**
     * Sets name_servers
     *
     * @param \Savvii\OpenproviderRest\Model\DomainNameserver[]|null $name_servers name_servers
     *
     * @return self
     */
    public function setNameServers($name_servers)
    {
        if (is_null($name_servers)) {
            throw new \InvalidArgumentException('non-nullable name_servers cannot be null');
        }
        $this->container['name_servers'] = $name_servers;

        return $this;
    }

    /**
     * Gets ns_group
     *
     * @return string|null
     */
    public function getNsGroup()
    {
        return $this->container['ns_group'];
    }

    /**
     * Sets ns_group
     *
     * @param string|null $ns_group ns_group
     *
     * @return self
     */
    public function setNsGroup($ns_group)
    {
        if (is_null($ns_group)) {
            throw new \InvalidArgumentException('non-nullable ns_group cannot be null');
        }
        $this->container['ns_group'] = $ns_group;

        return $this;
    }

    /**
     * Gets ns_template_id
     *
     * @return int|null
     */
    public function getNsTemplateId()
    {
        return $this->container['ns_template_id'];
    }

    /**
     * Sets ns_template_id
     *
     * @param int|null $ns_template_id ns_template_id
     *
     * @return self
     */
    public function setNsTemplateId($ns_template_id)
    {
        if (is_null($ns_template_id)) {
            throw new \InvalidArgumentException('non-nullable ns_template_id cannot be null');
        }
        $this->container['ns_template_id'] = $ns_template_id;

        return $this;
    }

    /**
     * Gets ns_template_name
     *
     * @return string|null
     */
    public function getNsTemplateName()
    {
        return $this->container['ns_template_name'];
    }

    /**
     * Sets ns_template_name
     *
     * @param string|null $ns_template_name ns_template_name
     *
     * @return self
     */
    public function setNsTemplateName($ns_template_name)
    {
        if (is_null($ns_template_name)) {
            throw new \InvalidArgumentException('non-nullable ns_template_name cannot be null');
        }
        $this->container['ns_template_name'] = $ns_template_name;

        return $this;
    }

    /**
     * Gets nsgroup_id
     *
     * @return int|null
     */
    public function getNsgroupId()
    {
        return $this->container['nsgroup_id'];
    }

    /**
     * Sets nsgroup_id
     *
     * @param int|null $nsgroup_id nsgroup_id
     *
     * @return self
     */
    public function setNsgroupId($nsgroup_id)
    {
        if (is_null($nsgroup_id)) {
            throw new \InvalidArgumentException('non-nullable nsgroup_id cannot be null');
        }
        $this->container['nsgroup_id'] = $nsgroup_id;

        return $this;
    }

    /**
     * Gets order_date
     *
     * @return string|null
     */
    public function getOrderDate()
    {
        return $this->container['order_date'];
    }

    /**
     * Sets order_date
     *
     * @param string|null $order_date order_date
     *
     * @return self
     */
    public function setOrderDate($order_date)
    {
        if (is_null($order_date)) {
            throw new \InvalidArgumentException('non-nullable order_date cannot be null');
        }
        $this->container['order_date'] = $order_date;

        return $this;
    }

    /**
     * Gets owner
     *
     * @return \Savvii\OpenproviderRest\Model\DomainOwner|null
     */
    public function getOwner()
    {
        return $this->container['owner'];
    }

    /**
     * Sets owner
     *
     * @param \Savvii\OpenproviderRest\Model\DomainOwner|null $owner owner
     *
     * @return self
     */
    public function setOwner($owner)
    {
        if (is_null($owner)) {
            throw new \InvalidArgumentException('non-nullable owner cannot be null');
        }
        $this->container['owner'] = $owner;

        return $this;
    }

    /**
     * Gets owner_company_name
     *
     * @return string|null
     */
    public function getOwnerCompanyName()
    {
        return $this->container['owner_company_name'];
    }

    /**
     * Sets owner_company_name
     *
     * @param string|null $owner_company_name owner_company_name
     *
     * @return self
     */
    public function setOwnerCompanyName($owner_company_name)
    {
        if (is_null($owner_company_name)) {
            throw new \InvalidArgumentException('non-nullable owner_company_name cannot be null');
        }
        $this->container['owner_company_name'] = $owner_company_name;

        return $this;
    }

    /**
     * Gets owner_handle
     *
     * @return string|null
     */
    public function getOwnerHandle()
    {
        return $this->container['owner_handle'];
    }

    /**
     * Sets owner_handle
     *
     * @param string|null $owner_handle owner_handle
     *
     * @return self
     */
    public function setOwnerHandle($owner_handle)
    {
        if (is_null($owner_handle)) {
            throw new \InvalidArgumentException('non-nullable owner_handle cannot be null');
        }
        $this->container['owner_handle'] = $owner_handle;

        return $this;
    }

    /**
     * Gets quarantine_expiration_date
     *
     * @return string|null
     */
    public function getQuarantineExpirationDate()
    {
        return $this->container['quarantine_expiration_date'];
    }

    /**
     * Sets quarantine_expiration_date
     *
     * @param string|null $quarantine_expiration_date quarantine_expiration_date
     *
     * @return self
     */
    public function setQuarantineExpirationDate($quarantine_expiration_date)
    {
        if (is_null($quarantine_expiration_date)) {
            throw new \InvalidArgumentException('non-nullable quarantine_expiration_date cannot be null');
        }
        $this->container['quarantine_expiration_date'] = $quarantine_expiration_date;

        return $this;
    }

    /**
     * Gets registry_expiration_date
     *
     * @return string|null
     */
    public function getRegistryExpirationDate()
    {
        return $this->container['registry_expiration_date'];
    }

    /**
     * Sets registry_expiration_date
     *
     * @param string|null $registry_expiration_date registry_expiration_date
     *
     * @return self
     */
    public function setRegistryExpirationDate($registry_expiration_date)
    {
        if (is_null($registry_expiration_date)) {
            throw new \InvalidArgumentException('non-nullable registry_expiration_date cannot be null');
        }
        $this->container['registry_expiration_date'] = $registry_expiration_date;

        return $this;
    }

    /**
     * Gets registry_statuses
     *
     * @return \Savvii\OpenproviderRest\Model\DomainRegistryStatuses|null
     */
    public function getRegistryStatuses()
    {
        return $this->container['registry_statuses'];
    }

    /**
     * Sets registry_statuses
     *
     * @param \Savvii\OpenproviderRest\Model\DomainRegistryStatuses|null $registry_statuses registry_statuses
     *
     * @return self
     */
    public function setRegistryStatuses($registry_statuses)
    {
        if (is_null($registry_statuses)) {
            throw new \InvalidArgumentException('non-nullable registry_statuses cannot be null');
        }
        $this->container['registry_statuses'] = $registry_statuses;

        return $this;
    }

    /**
     * Gets renew
     *
     * @return int|null
     */
    public function getRenew()
    {
        return $this->container['renew'];
    }

    /**
     * Sets renew
     *
     * @param int|null $renew renew
     *
     * @return self
     */
    public function setRenew($renew)
    {
        if (is_null($renew)) {
            throw new \InvalidArgumentException('non-nullable renew cannot be null');
        }
        $this->container['renew'] = $renew;

        return $this;
    }

    /**
     * Gets renewal_date
     *
     * @return string|null
     */
    public function getRenewalDate()
    {
        return $this->container['renewal_date'];
    }

    /**
     * Sets renewal_date
     *
     * @param string|null $renewal_date renewal_date
     *
     * @return self
     */
    public function setRenewalDate($renewal_date)
    {
        if (is_null($renewal_date)) {
            throw new \InvalidArgumentException('non-nullable renewal_date cannot be null');
        }
        $this->container['renewal_date'] = $renewal_date;

        return $this;
    }

    /**
     * Gets reseller_handle
     *
     * @return string|null
     */
    public function getResellerHandle()
    {
        return $this->container['reseller_handle'];
    }

    /**
     * Sets reseller_handle
     *
     * @param string|null $reseller_handle reseller_handle
     *
     * @return self
     */
    public function setResellerHandle($reseller_handle)
    {
        if (is_null($reseller_handle)) {
            throw new \InvalidArgumentException('non-nullable reseller_handle cannot be null');
        }
        $this->container['reseller_handle'] = $reseller_handle;

        return $this;
    }

    /**
     * Gets reseller_id
     *
     * @return int|null
     */
    public function getResellerId()
    {
        return $this->container['reseller_id'];
    }

    /**
     * Sets reseller_id
     *
     * @param int|null $reseller_id reseller_id
     *
     * @return self
     */
    public function setResellerId($reseller_id)
    {
        if (is_null($reseller_id)) {
            throw new \InvalidArgumentException('non-nullable reseller_id cannot be null');
        }
        $this->container['reseller_id'] = $reseller_id;

        return $this;
    }

    /**
     * Gets restorable_until
     *
     * @return string|null
     */
    public function getRestorableUntil()
    {
        return $this->container['restorable_until'];
    }

    /**
     * Sets restorable_until
     *
     * @param string|null $restorable_until restorable_until
     *
     * @return self
     */
    public function setRestorableUntil($restorable_until)
    {
        if (is_null($restorable_until)) {
            throw new \InvalidArgumentException('non-nullable restorable_until cannot be null');
        }
        $this->container['restorable_until'] = $restorable_until;

        return $this;
    }

    /**
     * Gets scheduled_at
     *
     * @return string|null
     */
    public function getScheduledAt()
    {
        return $this->container['scheduled_at'];
    }

    /**
     * Sets scheduled_at
     *
     * @param string|null $scheduled_at scheduled_at
     *
     * @return self
     */
    public function setScheduledAt($scheduled_at)
    {
        if (is_null($scheduled_at)) {
            throw new \InvalidArgumentException('non-nullable scheduled_at cannot be null');
        }
        $this->container['scheduled_at'] = $scheduled_at;

        return $this;
    }

    /**
     * Gets scheduled_from
     *
     * @return string|null
     */
    public function getScheduledFrom()
    {
        return $this->container['scheduled_from'];
    }

    /**
     * Sets scheduled_from
     *
     * @param string|null $scheduled_from scheduled_from
     *
     * @return self
     */
    public function setScheduledFrom($scheduled_from)
    {
        if (is_null($scheduled_from)) {
            throw new \InvalidArgumentException('non-nullable scheduled_from cannot be null');
        }
        $this->container['scheduled_from'] = $scheduled_from;

        return $this;
    }

    /**
     * Gets soft_quarantine_expiry_date
     *
     * @return string|null
     */
    public function getSoftQuarantineExpiryDate()
    {
        return $this->container['soft_quarantine_expiry_date'];
    }

    /**
     * Sets soft_quarantine_expiry_date
     *
     * @param string|null $soft_quarantine_expiry_date soft_quarantine_expiry_date
     *
     * @return self
     */
    public function setSoftQuarantineExpiryDate($soft_quarantine_expiry_date)
    {
        if (is_null($soft_quarantine_expiry_date)) {
            throw new \InvalidArgumentException('non-nullable soft_quarantine_expiry_date cannot be null');
        }
        $this->container['soft_quarantine_expiry_date'] = $soft_quarantine_expiry_date;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets tech_handle
     *
     * @return string|null
     */
    public function getTechHandle()
    {
        return $this->container['tech_handle'];
    }

    /**
     * Sets tech_handle
     *
     * @param string|null $tech_handle tech_handle
     *
     * @return self
     */
    public function setTechHandle($tech_handle)
    {
        if (is_null($tech_handle)) {
            throw new \InvalidArgumentException('non-nullable tech_handle cannot be null');
        }
        $this->container['tech_handle'] = $tech_handle;

        return $this;
    }

    /**
     * Gets trade_allowed
     *
     * @return bool|null
     */
    public function getTradeAllowed()
    {
        return $this->container['trade_allowed'];
    }

    /**
     * Sets trade_allowed
     *
     * @param bool|null $trade_allowed trade_allowed
     *
     * @return self
     */
    public function setTradeAllowed($trade_allowed)
    {
        if (is_null($trade_allowed)) {
            throw new \InvalidArgumentException('non-nullable trade_allowed cannot be null');
        }
        $this->container['trade_allowed'] = $trade_allowed;

        return $this;
    }

    /**
     * Gets trade_auth_code_required
     *
     * @return string|null
     */
    public function getTradeAuthCodeRequired()
    {
        return $this->container['trade_auth_code_required'];
    }

    /**
     * Sets trade_auth_code_required
     *
     * @param string|null $trade_auth_code_required trade_auth_code_required
     *
     * @return self
     */
    public function setTradeAuthCodeRequired($trade_auth_code_required)
    {
        if (is_null($trade_auth_code_required)) {
            throw new \InvalidArgumentException('non-nullable trade_auth_code_required cannot be null');
        }
        $this->container['trade_auth_code_required'] = $trade_auth_code_required;

        return $this;
    }

    /**
     * Gets transfer_auth_code_required
     *
     * @return string|null
     */
    public function getTransferAuthCodeRequired()
    {
        return $this->container['transfer_auth_code_required'];
    }

    /**
     * Sets transfer_auth_code_required
     *
     * @param string|null $transfer_auth_code_required transfer_auth_code_required
     *
     * @return self
     */
    public function setTransferAuthCodeRequired($transfer_auth_code_required)
    {
        if (is_null($transfer_auth_code_required)) {
            throw new \InvalidArgumentException('non-nullable transfer_auth_code_required cannot be null');
        }
        $this->container['transfer_auth_code_required'] = $transfer_auth_code_required;

        return $this;
    }

    /**
     * Gets transfer_cancel_supported
     *
     * @return bool|null
     */
    public function getTransferCancelSupported()
    {
        return $this->container['transfer_cancel_supported'];
    }

    /**
     * Sets transfer_cancel_supported
     *
     * @param bool|null $transfer_cancel_supported transfer_cancel_supported
     *
     * @return self
     */
    public function setTransferCancelSupported($transfer_cancel_supported)
    {
        if (is_null($transfer_cancel_supported)) {
            throw new \InvalidArgumentException('non-nullable transfer_cancel_supported cannot be null');
        }
        $this->container['transfer_cancel_supported'] = $transfer_cancel_supported;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets unit
     *
     * @return string|null
     */
    public function getUnit()
    {
        return $this->container['unit'];
    }

    /**
     * Sets unit
     *
     * @param string|null $unit unit
     *
     * @return self
     */
    public function setUnit($unit)
    {
        if (is_null($unit)) {
            throw new \InvalidArgumentException('non-nullable unit cannot be null');
        }
        $this->container['unit'] = $unit;

        return $this;
    }

    /**
     * Gets use_domicile
     *
     * @return bool|null
     */
    public function getUseDomicile()
    {
        return $this->container['use_domicile'];
    }

    /**
     * Sets use_domicile
     *
     * @param bool|null $use_domicile use_domicile
     *
     * @return self
     */
    public function setUseDomicile($use_domicile)
    {
        if (is_null($use_domicile)) {
            throw new \InvalidArgumentException('non-nullable use_domicile cannot be null');
        }
        $this->container['use_domicile'] = $use_domicile;

        return $this;
    }

    /**
     * Gets verification_email_exp_date
     *
     * @return string|null
     */
    public function getVerificationEmailExpDate()
    {
        return $this->container['verification_email_exp_date'];
    }

    /**
     * Sets verification_email_exp_date
     *
     * @param string|null $verification_email_exp_date verification_email_exp_date
     *
     * @return self
     */
    public function setVerificationEmailExpDate($verification_email_exp_date)
    {
        if (is_null($verification_email_exp_date)) {
            throw new \InvalidArgumentException('non-nullable verification_email_exp_date cannot be null');
        }
        $this->container['verification_email_exp_date'] = $verification_email_exp_date;

        return $this;
    }

    /**
     * Gets verification_email_name
     *
     * @return string|null
     */
    public function getVerificationEmailName()
    {
        return $this->container['verification_email_name'];
    }

    /**
     * Sets verification_email_name
     *
     * @param string|null $verification_email_name verification_email_name
     *
     * @return self
     */
    public function setVerificationEmailName($verification_email_name)
    {
        if (is_null($verification_email_name)) {
            throw new \InvalidArgumentException('non-nullable verification_email_name cannot be null');
        }
        $this->container['verification_email_name'] = $verification_email_name;

        return $this;
    }

    /**
     * Gets verification_email_status
     *
     * @return string|null
     */
    public function getVerificationEmailStatus()
    {
        return $this->container['verification_email_status'];
    }

    /**
     * Sets verification_email_status
     *
     * @param string|null $verification_email_status verification_email_status
     *
     * @return self
     */
    public function setVerificationEmailStatus($verification_email_status)
    {
        if (is_null($verification_email_status)) {
            throw new \InvalidArgumentException('non-nullable verification_email_status cannot be null');
        }
        $this->container['verification_email_status'] = $verification_email_status;

        return $this;
    }

    /**
     * Gets verification_email_status_description
     *
     * @return string|null
     */
    public function getVerificationEmailStatusDescription()
    {
        return $this->container['verification_email_status_description'];
    }

    /**
     * Sets verification_email_status_description
     *
     * @param string|null $verification_email_status_description verification_email_status_description
     *
     * @return self
     */
    public function setVerificationEmailStatusDescription($verification_email_status_description)
    {
        if (is_null($verification_email_status_description)) {
            throw new \InvalidArgumentException('non-nullable verification_email_status_description cannot be null');
        }
        $this->container['verification_email_status_description'] = $verification_email_status_description;

        return $this;
    }

    /**
     * Gets whois_privacy_data
     *
     * @return \Savvii\OpenproviderRest\Model\DomainWhoisPrivacyData|null
     */
    public function getWhoisPrivacyData()
    {
        return $this->container['whois_privacy_data'];
    }

    /**
     * Sets whois_privacy_data
     *
     * @param \Savvii\OpenproviderRest\Model\DomainWhoisPrivacyData|null $whois_privacy_data whois_privacy_data
     *
     * @return self
     */
    public function setWhoisPrivacyData($whois_privacy_data)
    {
        if (is_null($whois_privacy_data)) {
            throw new \InvalidArgumentException('non-nullable whois_privacy_data cannot be null');
        }
        $this->container['whois_privacy_data'] = $whois_privacy_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


