<?php
/**
 * SettingsGetSettingsResponseData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Savvii\OpenproviderRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savvii\OpenproviderRest\Model;

use \ArrayAccess;
use \Savvii\OpenproviderRest\ObjectSerializer;

/**
 * SettingsGetSettingsResponseData Class Doc Comment
 *
 * @category Class
 * @package  Savvii\OpenproviderRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SettingsGetSettingsResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'settingsGetSettingsResponseData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'av_handle' => 'string',
        'claims_confirm_url' => 'string',
        'claims_email_subject' => 'string',
        'claims_reseller_name' => 'string',
        'claims_sender_email' => 'string',
        'currency' => 'string',
        'default_domain_billing_handle' => 'string',
        'default_domain_reseller_handle' => 'string',
        'foa_confirm_url' => 'string',
        'foa_email_subject' => 'string',
        'foa_reseller_name' => 'string',
        'foa_sender_email' => 'string',
        'foa_terms_conditions_url' => 'string',
        'is_auto_renew_enabled' => 'bool',
        'is_custom_nses_enabled' => 'bool',
        'ive2_customized_body' => 'string',
        'ive2_email_subject' => 'string',
        'ive_confirm_url' => 'string',
        'ive_customized_body' => 'string',
        'ive_email_subject' => 'string',
        'ive_reseller_name' => 'string',
        'ive_sender_email' => 'string',
        'jurisdiction' => 'string',
        'language' => 'string',
        'maximum_credit' => 'float',
        'maximum_credit_card_payment' => 'float',
        'maximum_i_deal_payment' => 'float',
        'maximum_western_union_payment' => 'float',
        'minimum_payment' => 'float',
        'minimum_western_union_payment' => 'float',
        'pay_methods' => 'string[]',
        'payment_methods' => '\Savvii\OpenproviderRest\Model\SettingsPaymentMethods[]',
        'preregistered_domain_priorities' => 'string',
        'recurring_payment_methods' => '\Savvii\OpenproviderRest\Model\SettingsPaymentMethods[]',
        'renew_notification_days' => 'int[]',
        'renew_notification_every_week' => 'bool',
        'signed_contracts' => '\Savvii\OpenproviderRest\Model\SettingsSignedContracts[]',
        'tac_contract' => '\Savvii\OpenproviderRest\Model\SettingsTacContract',
        'tags' => 'string[]',
        'transaction_fee' => '\Savvii\OpenproviderRest\Model\SettingsTransactionFee',
        'type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'av_handle' => null,
        'claims_confirm_url' => null,
        'claims_email_subject' => null,
        'claims_reseller_name' => null,
        'claims_sender_email' => null,
        'currency' => null,
        'default_domain_billing_handle' => null,
        'default_domain_reseller_handle' => null,
        'foa_confirm_url' => null,
        'foa_email_subject' => null,
        'foa_reseller_name' => null,
        'foa_sender_email' => null,
        'foa_terms_conditions_url' => null,
        'is_auto_renew_enabled' => 'boolean',
        'is_custom_nses_enabled' => 'boolean',
        'ive2_customized_body' => null,
        'ive2_email_subject' => null,
        'ive_confirm_url' => null,
        'ive_customized_body' => null,
        'ive_email_subject' => null,
        'ive_reseller_name' => null,
        'ive_sender_email' => null,
        'jurisdiction' => null,
        'language' => null,
        'maximum_credit' => 'double',
        'maximum_credit_card_payment' => 'double',
        'maximum_i_deal_payment' => 'double',
        'maximum_western_union_payment' => 'double',
        'minimum_payment' => 'double',
        'minimum_western_union_payment' => 'double',
        'pay_methods' => null,
        'payment_methods' => null,
        'preregistered_domain_priorities' => null,
        'recurring_payment_methods' => null,
        'renew_notification_days' => 'int32',
        'renew_notification_every_week' => 'boolean',
        'signed_contracts' => null,
        'tac_contract' => null,
        'tags' => null,
        'transaction_fee' => null,
        'type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'av_handle' => false,
		'claims_confirm_url' => false,
		'claims_email_subject' => false,
		'claims_reseller_name' => false,
		'claims_sender_email' => false,
		'currency' => false,
		'default_domain_billing_handle' => false,
		'default_domain_reseller_handle' => false,
		'foa_confirm_url' => false,
		'foa_email_subject' => false,
		'foa_reseller_name' => false,
		'foa_sender_email' => false,
		'foa_terms_conditions_url' => false,
		'is_auto_renew_enabled' => false,
		'is_custom_nses_enabled' => false,
		'ive2_customized_body' => false,
		'ive2_email_subject' => false,
		'ive_confirm_url' => false,
		'ive_customized_body' => false,
		'ive_email_subject' => false,
		'ive_reseller_name' => false,
		'ive_sender_email' => false,
		'jurisdiction' => false,
		'language' => false,
		'maximum_credit' => false,
		'maximum_credit_card_payment' => false,
		'maximum_i_deal_payment' => false,
		'maximum_western_union_payment' => false,
		'minimum_payment' => false,
		'minimum_western_union_payment' => false,
		'pay_methods' => false,
		'payment_methods' => false,
		'preregistered_domain_priorities' => false,
		'recurring_payment_methods' => false,
		'renew_notification_days' => false,
		'renew_notification_every_week' => false,
		'signed_contracts' => false,
		'tac_contract' => false,
		'tags' => false,
		'transaction_fee' => false,
		'type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'av_handle' => 'av_handle',
        'claims_confirm_url' => 'claims_confirm_url',
        'claims_email_subject' => 'claims_email_subject',
        'claims_reseller_name' => 'claims_reseller_name',
        'claims_sender_email' => 'claims_sender_email',
        'currency' => 'currency',
        'default_domain_billing_handle' => 'default_domain_billing_handle',
        'default_domain_reseller_handle' => 'default_domain_reseller_handle',
        'foa_confirm_url' => 'foa_confirm_url',
        'foa_email_subject' => 'foa_email_subject',
        'foa_reseller_name' => 'foa_reseller_name',
        'foa_sender_email' => 'foa_sender_email',
        'foa_terms_conditions_url' => 'foa_terms_conditions_url',
        'is_auto_renew_enabled' => 'is_auto_renew_enabled',
        'is_custom_nses_enabled' => 'is_custom_nses_enabled',
        'ive2_customized_body' => 'ive2_customized_body',
        'ive2_email_subject' => 'ive2_email_subject',
        'ive_confirm_url' => 'ive_confirm_url',
        'ive_customized_body' => 'ive_customized_body',
        'ive_email_subject' => 'ive_email_subject',
        'ive_reseller_name' => 'ive_reseller_name',
        'ive_sender_email' => 'ive_sender_email',
        'jurisdiction' => 'jurisdiction',
        'language' => 'language',
        'maximum_credit' => 'maximum_credit',
        'maximum_credit_card_payment' => 'maximum_credit_card_payment',
        'maximum_i_deal_payment' => 'maximum_i_deal_payment',
        'maximum_western_union_payment' => 'maximum_western_union_payment',
        'minimum_payment' => 'minimum_payment',
        'minimum_western_union_payment' => 'minimum_western_union_payment',
        'pay_methods' => 'pay_methods',
        'payment_methods' => 'payment_methods',
        'preregistered_domain_priorities' => 'preregistered_domain_priorities',
        'recurring_payment_methods' => 'recurring_payment_methods',
        'renew_notification_days' => 'renew_notification_days',
        'renew_notification_every_week' => 'renew_notification_every_week',
        'signed_contracts' => 'signed_contracts',
        'tac_contract' => 'tac_contract',
        'tags' => 'tags',
        'transaction_fee' => 'transaction_fee',
        'type' => 'type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'av_handle' => 'setAvHandle',
        'claims_confirm_url' => 'setClaimsConfirmUrl',
        'claims_email_subject' => 'setClaimsEmailSubject',
        'claims_reseller_name' => 'setClaimsResellerName',
        'claims_sender_email' => 'setClaimsSenderEmail',
        'currency' => 'setCurrency',
        'default_domain_billing_handle' => 'setDefaultDomainBillingHandle',
        'default_domain_reseller_handle' => 'setDefaultDomainResellerHandle',
        'foa_confirm_url' => 'setFoaConfirmUrl',
        'foa_email_subject' => 'setFoaEmailSubject',
        'foa_reseller_name' => 'setFoaResellerName',
        'foa_sender_email' => 'setFoaSenderEmail',
        'foa_terms_conditions_url' => 'setFoaTermsConditionsUrl',
        'is_auto_renew_enabled' => 'setIsAutoRenewEnabled',
        'is_custom_nses_enabled' => 'setIsCustomNsesEnabled',
        'ive2_customized_body' => 'setIve2CustomizedBody',
        'ive2_email_subject' => 'setIve2EmailSubject',
        'ive_confirm_url' => 'setIveConfirmUrl',
        'ive_customized_body' => 'setIveCustomizedBody',
        'ive_email_subject' => 'setIveEmailSubject',
        'ive_reseller_name' => 'setIveResellerName',
        'ive_sender_email' => 'setIveSenderEmail',
        'jurisdiction' => 'setJurisdiction',
        'language' => 'setLanguage',
        'maximum_credit' => 'setMaximumCredit',
        'maximum_credit_card_payment' => 'setMaximumCreditCardPayment',
        'maximum_i_deal_payment' => 'setMaximumIDealPayment',
        'maximum_western_union_payment' => 'setMaximumWesternUnionPayment',
        'minimum_payment' => 'setMinimumPayment',
        'minimum_western_union_payment' => 'setMinimumWesternUnionPayment',
        'pay_methods' => 'setPayMethods',
        'payment_methods' => 'setPaymentMethods',
        'preregistered_domain_priorities' => 'setPreregisteredDomainPriorities',
        'recurring_payment_methods' => 'setRecurringPaymentMethods',
        'renew_notification_days' => 'setRenewNotificationDays',
        'renew_notification_every_week' => 'setRenewNotificationEveryWeek',
        'signed_contracts' => 'setSignedContracts',
        'tac_contract' => 'setTacContract',
        'tags' => 'setTags',
        'transaction_fee' => 'setTransactionFee',
        'type' => 'setType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'av_handle' => 'getAvHandle',
        'claims_confirm_url' => 'getClaimsConfirmUrl',
        'claims_email_subject' => 'getClaimsEmailSubject',
        'claims_reseller_name' => 'getClaimsResellerName',
        'claims_sender_email' => 'getClaimsSenderEmail',
        'currency' => 'getCurrency',
        'default_domain_billing_handle' => 'getDefaultDomainBillingHandle',
        'default_domain_reseller_handle' => 'getDefaultDomainResellerHandle',
        'foa_confirm_url' => 'getFoaConfirmUrl',
        'foa_email_subject' => 'getFoaEmailSubject',
        'foa_reseller_name' => 'getFoaResellerName',
        'foa_sender_email' => 'getFoaSenderEmail',
        'foa_terms_conditions_url' => 'getFoaTermsConditionsUrl',
        'is_auto_renew_enabled' => 'getIsAutoRenewEnabled',
        'is_custom_nses_enabled' => 'getIsCustomNsesEnabled',
        'ive2_customized_body' => 'getIve2CustomizedBody',
        'ive2_email_subject' => 'getIve2EmailSubject',
        'ive_confirm_url' => 'getIveConfirmUrl',
        'ive_customized_body' => 'getIveCustomizedBody',
        'ive_email_subject' => 'getIveEmailSubject',
        'ive_reseller_name' => 'getIveResellerName',
        'ive_sender_email' => 'getIveSenderEmail',
        'jurisdiction' => 'getJurisdiction',
        'language' => 'getLanguage',
        'maximum_credit' => 'getMaximumCredit',
        'maximum_credit_card_payment' => 'getMaximumCreditCardPayment',
        'maximum_i_deal_payment' => 'getMaximumIDealPayment',
        'maximum_western_union_payment' => 'getMaximumWesternUnionPayment',
        'minimum_payment' => 'getMinimumPayment',
        'minimum_western_union_payment' => 'getMinimumWesternUnionPayment',
        'pay_methods' => 'getPayMethods',
        'payment_methods' => 'getPaymentMethods',
        'preregistered_domain_priorities' => 'getPreregisteredDomainPriorities',
        'recurring_payment_methods' => 'getRecurringPaymentMethods',
        'renew_notification_days' => 'getRenewNotificationDays',
        'renew_notification_every_week' => 'getRenewNotificationEveryWeek',
        'signed_contracts' => 'getSignedContracts',
        'tac_contract' => 'getTacContract',
        'tags' => 'getTags',
        'transaction_fee' => 'getTransactionFee',
        'type' => 'getType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('av_handle', $data ?? [], null);
        $this->setIfExists('claims_confirm_url', $data ?? [], null);
        $this->setIfExists('claims_email_subject', $data ?? [], null);
        $this->setIfExists('claims_reseller_name', $data ?? [], null);
        $this->setIfExists('claims_sender_email', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('default_domain_billing_handle', $data ?? [], null);
        $this->setIfExists('default_domain_reseller_handle', $data ?? [], null);
        $this->setIfExists('foa_confirm_url', $data ?? [], null);
        $this->setIfExists('foa_email_subject', $data ?? [], null);
        $this->setIfExists('foa_reseller_name', $data ?? [], null);
        $this->setIfExists('foa_sender_email', $data ?? [], null);
        $this->setIfExists('foa_terms_conditions_url', $data ?? [], null);
        $this->setIfExists('is_auto_renew_enabled', $data ?? [], null);
        $this->setIfExists('is_custom_nses_enabled', $data ?? [], null);
        $this->setIfExists('ive2_customized_body', $data ?? [], null);
        $this->setIfExists('ive2_email_subject', $data ?? [], null);
        $this->setIfExists('ive_confirm_url', $data ?? [], null);
        $this->setIfExists('ive_customized_body', $data ?? [], null);
        $this->setIfExists('ive_email_subject', $data ?? [], null);
        $this->setIfExists('ive_reseller_name', $data ?? [], null);
        $this->setIfExists('ive_sender_email', $data ?? [], null);
        $this->setIfExists('jurisdiction', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('maximum_credit', $data ?? [], null);
        $this->setIfExists('maximum_credit_card_payment', $data ?? [], null);
        $this->setIfExists('maximum_i_deal_payment', $data ?? [], null);
        $this->setIfExists('maximum_western_union_payment', $data ?? [], null);
        $this->setIfExists('minimum_payment', $data ?? [], null);
        $this->setIfExists('minimum_western_union_payment', $data ?? [], null);
        $this->setIfExists('pay_methods', $data ?? [], null);
        $this->setIfExists('payment_methods', $data ?? [], null);
        $this->setIfExists('preregistered_domain_priorities', $data ?? [], null);
        $this->setIfExists('recurring_payment_methods', $data ?? [], null);
        $this->setIfExists('renew_notification_days', $data ?? [], null);
        $this->setIfExists('renew_notification_every_week', $data ?? [], null);
        $this->setIfExists('signed_contracts', $data ?? [], null);
        $this->setIfExists('tac_contract', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('transaction_fee', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets av_handle
     *
     * @return string|null
     */
    public function getAvHandle()
    {
        return $this->container['av_handle'];
    }

    /**
     * Sets av_handle
     *
     * @param string|null $av_handle av_handle
     *
     * @return self
     */
    public function setAvHandle($av_handle)
    {
        if (is_null($av_handle)) {
            throw new \InvalidArgumentException('non-nullable av_handle cannot be null');
        }
        $this->container['av_handle'] = $av_handle;

        return $this;
    }

    /**
     * Gets claims_confirm_url
     *
     * @return string|null
     */
    public function getClaimsConfirmUrl()
    {
        return $this->container['claims_confirm_url'];
    }

    /**
     * Sets claims_confirm_url
     *
     * @param string|null $claims_confirm_url claims_confirm_url
     *
     * @return self
     */
    public function setClaimsConfirmUrl($claims_confirm_url)
    {
        if (is_null($claims_confirm_url)) {
            throw new \InvalidArgumentException('non-nullable claims_confirm_url cannot be null');
        }
        $this->container['claims_confirm_url'] = $claims_confirm_url;

        return $this;
    }

    /**
     * Gets claims_email_subject
     *
     * @return string|null
     */
    public function getClaimsEmailSubject()
    {
        return $this->container['claims_email_subject'];
    }

    /**
     * Sets claims_email_subject
     *
     * @param string|null $claims_email_subject claims_email_subject
     *
     * @return self
     */
    public function setClaimsEmailSubject($claims_email_subject)
    {
        if (is_null($claims_email_subject)) {
            throw new \InvalidArgumentException('non-nullable claims_email_subject cannot be null');
        }
        $this->container['claims_email_subject'] = $claims_email_subject;

        return $this;
    }

    /**
     * Gets claims_reseller_name
     *
     * @return string|null
     */
    public function getClaimsResellerName()
    {
        return $this->container['claims_reseller_name'];
    }

    /**
     * Sets claims_reseller_name
     *
     * @param string|null $claims_reseller_name claims_reseller_name
     *
     * @return self
     */
    public function setClaimsResellerName($claims_reseller_name)
    {
        if (is_null($claims_reseller_name)) {
            throw new \InvalidArgumentException('non-nullable claims_reseller_name cannot be null');
        }
        $this->container['claims_reseller_name'] = $claims_reseller_name;

        return $this;
    }

    /**
     * Gets claims_sender_email
     *
     * @return string|null
     */
    public function getClaimsSenderEmail()
    {
        return $this->container['claims_sender_email'];
    }

    /**
     * Sets claims_sender_email
     *
     * @param string|null $claims_sender_email claims_sender_email
     *
     * @return self
     */
    public function setClaimsSenderEmail($claims_sender_email)
    {
        if (is_null($claims_sender_email)) {
            throw new \InvalidArgumentException('non-nullable claims_sender_email cannot be null');
        }
        $this->container['claims_sender_email'] = $claims_sender_email;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets default_domain_billing_handle
     *
     * @return string|null
     */
    public function getDefaultDomainBillingHandle()
    {
        return $this->container['default_domain_billing_handle'];
    }

    /**
     * Sets default_domain_billing_handle
     *
     * @param string|null $default_domain_billing_handle default_domain_billing_handle
     *
     * @return self
     */
    public function setDefaultDomainBillingHandle($default_domain_billing_handle)
    {
        if (is_null($default_domain_billing_handle)) {
            throw new \InvalidArgumentException('non-nullable default_domain_billing_handle cannot be null');
        }
        $this->container['default_domain_billing_handle'] = $default_domain_billing_handle;

        return $this;
    }

    /**
     * Gets default_domain_reseller_handle
     *
     * @return string|null
     */
    public function getDefaultDomainResellerHandle()
    {
        return $this->container['default_domain_reseller_handle'];
    }

    /**
     * Sets default_domain_reseller_handle
     *
     * @param string|null $default_domain_reseller_handle default_domain_reseller_handle
     *
     * @return self
     */
    public function setDefaultDomainResellerHandle($default_domain_reseller_handle)
    {
        if (is_null($default_domain_reseller_handle)) {
            throw new \InvalidArgumentException('non-nullable default_domain_reseller_handle cannot be null');
        }
        $this->container['default_domain_reseller_handle'] = $default_domain_reseller_handle;

        return $this;
    }

    /**
     * Gets foa_confirm_url
     *
     * @return string|null
     */
    public function getFoaConfirmUrl()
    {
        return $this->container['foa_confirm_url'];
    }

    /**
     * Sets foa_confirm_url
     *
     * @param string|null $foa_confirm_url foa_confirm_url
     *
     * @return self
     */
    public function setFoaConfirmUrl($foa_confirm_url)
    {
        if (is_null($foa_confirm_url)) {
            throw new \InvalidArgumentException('non-nullable foa_confirm_url cannot be null');
        }
        $this->container['foa_confirm_url'] = $foa_confirm_url;

        return $this;
    }

    /**
     * Gets foa_email_subject
     *
     * @return string|null
     */
    public function getFoaEmailSubject()
    {
        return $this->container['foa_email_subject'];
    }

    /**
     * Sets foa_email_subject
     *
     * @param string|null $foa_email_subject foa_email_subject
     *
     * @return self
     */
    public function setFoaEmailSubject($foa_email_subject)
    {
        if (is_null($foa_email_subject)) {
            throw new \InvalidArgumentException('non-nullable foa_email_subject cannot be null');
        }
        $this->container['foa_email_subject'] = $foa_email_subject;

        return $this;
    }

    /**
     * Gets foa_reseller_name
     *
     * @return string|null
     */
    public function getFoaResellerName()
    {
        return $this->container['foa_reseller_name'];
    }

    /**
     * Sets foa_reseller_name
     *
     * @param string|null $foa_reseller_name foa_reseller_name
     *
     * @return self
     */
    public function setFoaResellerName($foa_reseller_name)
    {
        if (is_null($foa_reseller_name)) {
            throw new \InvalidArgumentException('non-nullable foa_reseller_name cannot be null');
        }
        $this->container['foa_reseller_name'] = $foa_reseller_name;

        return $this;
    }

    /**
     * Gets foa_sender_email
     *
     * @return string|null
     */
    public function getFoaSenderEmail()
    {
        return $this->container['foa_sender_email'];
    }

    /**
     * Sets foa_sender_email
     *
     * @param string|null $foa_sender_email foa_sender_email
     *
     * @return self
     */
    public function setFoaSenderEmail($foa_sender_email)
    {
        if (is_null($foa_sender_email)) {
            throw new \InvalidArgumentException('non-nullable foa_sender_email cannot be null');
        }
        $this->container['foa_sender_email'] = $foa_sender_email;

        return $this;
    }

    /**
     * Gets foa_terms_conditions_url
     *
     * @return string|null
     */
    public function getFoaTermsConditionsUrl()
    {
        return $this->container['foa_terms_conditions_url'];
    }

    /**
     * Sets foa_terms_conditions_url
     *
     * @param string|null $foa_terms_conditions_url foa_terms_conditions_url
     *
     * @return self
     */
    public function setFoaTermsConditionsUrl($foa_terms_conditions_url)
    {
        if (is_null($foa_terms_conditions_url)) {
            throw new \InvalidArgumentException('non-nullable foa_terms_conditions_url cannot be null');
        }
        $this->container['foa_terms_conditions_url'] = $foa_terms_conditions_url;

        return $this;
    }

    /**
     * Gets is_auto_renew_enabled
     *
     * @return bool|null
     */
    public function getIsAutoRenewEnabled()
    {
        return $this->container['is_auto_renew_enabled'];
    }

    /**
     * Sets is_auto_renew_enabled
     *
     * @param bool|null $is_auto_renew_enabled is_auto_renew_enabled
     *
     * @return self
     */
    public function setIsAutoRenewEnabled($is_auto_renew_enabled)
    {
        if (is_null($is_auto_renew_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_auto_renew_enabled cannot be null');
        }
        $this->container['is_auto_renew_enabled'] = $is_auto_renew_enabled;

        return $this;
    }

    /**
     * Gets is_custom_nses_enabled
     *
     * @return bool|null
     */
    public function getIsCustomNsesEnabled()
    {
        return $this->container['is_custom_nses_enabled'];
    }

    /**
     * Sets is_custom_nses_enabled
     *
     * @param bool|null $is_custom_nses_enabled is_custom_nses_enabled
     *
     * @return self
     */
    public function setIsCustomNsesEnabled($is_custom_nses_enabled)
    {
        if (is_null($is_custom_nses_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_custom_nses_enabled cannot be null');
        }
        $this->container['is_custom_nses_enabled'] = $is_custom_nses_enabled;

        return $this;
    }

    /**
     * Gets ive2_customized_body
     *
     * @return string|null
     */
    public function getIve2CustomizedBody()
    {
        return $this->container['ive2_customized_body'];
    }

    /**
     * Sets ive2_customized_body
     *
     * @param string|null $ive2_customized_body ive2_customized_body
     *
     * @return self
     */
    public function setIve2CustomizedBody($ive2_customized_body)
    {
        if (is_null($ive2_customized_body)) {
            throw new \InvalidArgumentException('non-nullable ive2_customized_body cannot be null');
        }
        $this->container['ive2_customized_body'] = $ive2_customized_body;

        return $this;
    }

    /**
     * Gets ive2_email_subject
     *
     * @return string|null
     */
    public function getIve2EmailSubject()
    {
        return $this->container['ive2_email_subject'];
    }

    /**
     * Sets ive2_email_subject
     *
     * @param string|null $ive2_email_subject ive2_email_subject
     *
     * @return self
     */
    public function setIve2EmailSubject($ive2_email_subject)
    {
        if (is_null($ive2_email_subject)) {
            throw new \InvalidArgumentException('non-nullable ive2_email_subject cannot be null');
        }
        $this->container['ive2_email_subject'] = $ive2_email_subject;

        return $this;
    }

    /**
     * Gets ive_confirm_url
     *
     * @return string|null
     */
    public function getIveConfirmUrl()
    {
        return $this->container['ive_confirm_url'];
    }

    /**
     * Sets ive_confirm_url
     *
     * @param string|null $ive_confirm_url ive_confirm_url
     *
     * @return self
     */
    public function setIveConfirmUrl($ive_confirm_url)
    {
        if (is_null($ive_confirm_url)) {
            throw new \InvalidArgumentException('non-nullable ive_confirm_url cannot be null');
        }
        $this->container['ive_confirm_url'] = $ive_confirm_url;

        return $this;
    }

    /**
     * Gets ive_customized_body
     *
     * @return string|null
     */
    public function getIveCustomizedBody()
    {
        return $this->container['ive_customized_body'];
    }

    /**
     * Sets ive_customized_body
     *
     * @param string|null $ive_customized_body ive_customized_body
     *
     * @return self
     */
    public function setIveCustomizedBody($ive_customized_body)
    {
        if (is_null($ive_customized_body)) {
            throw new \InvalidArgumentException('non-nullable ive_customized_body cannot be null');
        }
        $this->container['ive_customized_body'] = $ive_customized_body;

        return $this;
    }

    /**
     * Gets ive_email_subject
     *
     * @return string|null
     */
    public function getIveEmailSubject()
    {
        return $this->container['ive_email_subject'];
    }

    /**
     * Sets ive_email_subject
     *
     * @param string|null $ive_email_subject ive_email_subject
     *
     * @return self
     */
    public function setIveEmailSubject($ive_email_subject)
    {
        if (is_null($ive_email_subject)) {
            throw new \InvalidArgumentException('non-nullable ive_email_subject cannot be null');
        }
        $this->container['ive_email_subject'] = $ive_email_subject;

        return $this;
    }

    /**
     * Gets ive_reseller_name
     *
     * @return string|null
     */
    public function getIveResellerName()
    {
        return $this->container['ive_reseller_name'];
    }

    /**
     * Sets ive_reseller_name
     *
     * @param string|null $ive_reseller_name ive_reseller_name
     *
     * @return self
     */
    public function setIveResellerName($ive_reseller_name)
    {
        if (is_null($ive_reseller_name)) {
            throw new \InvalidArgumentException('non-nullable ive_reseller_name cannot be null');
        }
        $this->container['ive_reseller_name'] = $ive_reseller_name;

        return $this;
    }

    /**
     * Gets ive_sender_email
     *
     * @return string|null
     */
    public function getIveSenderEmail()
    {
        return $this->container['ive_sender_email'];
    }

    /**
     * Sets ive_sender_email
     *
     * @param string|null $ive_sender_email ive_sender_email
     *
     * @return self
     */
    public function setIveSenderEmail($ive_sender_email)
    {
        if (is_null($ive_sender_email)) {
            throw new \InvalidArgumentException('non-nullable ive_sender_email cannot be null');
        }
        $this->container['ive_sender_email'] = $ive_sender_email;

        return $this;
    }

    /**
     * Gets jurisdiction
     *
     * @return string|null
     */
    public function getJurisdiction()
    {
        return $this->container['jurisdiction'];
    }

    /**
     * Sets jurisdiction
     *
     * @param string|null $jurisdiction jurisdiction
     *
     * @return self
     */
    public function setJurisdiction($jurisdiction)
    {
        if (is_null($jurisdiction)) {
            throw new \InvalidArgumentException('non-nullable jurisdiction cannot be null');
        }
        $this->container['jurisdiction'] = $jurisdiction;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets maximum_credit
     *
     * @return float|null
     */
    public function getMaximumCredit()
    {
        return $this->container['maximum_credit'];
    }

    /**
     * Sets maximum_credit
     *
     * @param float|null $maximum_credit maximum_credit
     *
     * @return self
     */
    public function setMaximumCredit($maximum_credit)
    {
        if (is_null($maximum_credit)) {
            throw new \InvalidArgumentException('non-nullable maximum_credit cannot be null');
        }
        $this->container['maximum_credit'] = $maximum_credit;

        return $this;
    }

    /**
     * Gets maximum_credit_card_payment
     *
     * @return float|null
     */
    public function getMaximumCreditCardPayment()
    {
        return $this->container['maximum_credit_card_payment'];
    }

    /**
     * Sets maximum_credit_card_payment
     *
     * @param float|null $maximum_credit_card_payment maximum_credit_card_payment
     *
     * @return self
     */
    public function setMaximumCreditCardPayment($maximum_credit_card_payment)
    {
        if (is_null($maximum_credit_card_payment)) {
            throw new \InvalidArgumentException('non-nullable maximum_credit_card_payment cannot be null');
        }
        $this->container['maximum_credit_card_payment'] = $maximum_credit_card_payment;

        return $this;
    }

    /**
     * Gets maximum_i_deal_payment
     *
     * @return float|null
     */
    public function getMaximumIDealPayment()
    {
        return $this->container['maximum_i_deal_payment'];
    }

    /**
     * Sets maximum_i_deal_payment
     *
     * @param float|null $maximum_i_deal_payment maximum_i_deal_payment
     *
     * @return self
     */
    public function setMaximumIDealPayment($maximum_i_deal_payment)
    {
        if (is_null($maximum_i_deal_payment)) {
            throw new \InvalidArgumentException('non-nullable maximum_i_deal_payment cannot be null');
        }
        $this->container['maximum_i_deal_payment'] = $maximum_i_deal_payment;

        return $this;
    }

    /**
     * Gets maximum_western_union_payment
     *
     * @return float|null
     */
    public function getMaximumWesternUnionPayment()
    {
        return $this->container['maximum_western_union_payment'];
    }

    /**
     * Sets maximum_western_union_payment
     *
     * @param float|null $maximum_western_union_payment maximum_western_union_payment
     *
     * @return self
     */
    public function setMaximumWesternUnionPayment($maximum_western_union_payment)
    {
        if (is_null($maximum_western_union_payment)) {
            throw new \InvalidArgumentException('non-nullable maximum_western_union_payment cannot be null');
        }
        $this->container['maximum_western_union_payment'] = $maximum_western_union_payment;

        return $this;
    }

    /**
     * Gets minimum_payment
     *
     * @return float|null
     */
    public function getMinimumPayment()
    {
        return $this->container['minimum_payment'];
    }

    /**
     * Sets minimum_payment
     *
     * @param float|null $minimum_payment minimum_payment
     *
     * @return self
     */
    public function setMinimumPayment($minimum_payment)
    {
        if (is_null($minimum_payment)) {
            throw new \InvalidArgumentException('non-nullable minimum_payment cannot be null');
        }
        $this->container['minimum_payment'] = $minimum_payment;

        return $this;
    }

    /**
     * Gets minimum_western_union_payment
     *
     * @return float|null
     */
    public function getMinimumWesternUnionPayment()
    {
        return $this->container['minimum_western_union_payment'];
    }

    /**
     * Sets minimum_western_union_payment
     *
     * @param float|null $minimum_western_union_payment minimum_western_union_payment
     *
     * @return self
     */
    public function setMinimumWesternUnionPayment($minimum_western_union_payment)
    {
        if (is_null($minimum_western_union_payment)) {
            throw new \InvalidArgumentException('non-nullable minimum_western_union_payment cannot be null');
        }
        $this->container['minimum_western_union_payment'] = $minimum_western_union_payment;

        return $this;
    }

    /**
     * Gets pay_methods
     *
     * @return string[]|null
     */
    public function getPayMethods()
    {
        return $this->container['pay_methods'];
    }

    /**
     * Sets pay_methods
     *
     * @param string[]|null $pay_methods pay_methods
     *
     * @return self
     */
    public function setPayMethods($pay_methods)
    {
        if (is_null($pay_methods)) {
            throw new \InvalidArgumentException('non-nullable pay_methods cannot be null');
        }
        $this->container['pay_methods'] = $pay_methods;

        return $this;
    }

    /**
     * Gets payment_methods
     *
     * @return \Savvii\OpenproviderRest\Model\SettingsPaymentMethods[]|null
     */
    public function getPaymentMethods()
    {
        return $this->container['payment_methods'];
    }

    /**
     * Sets payment_methods
     *
     * @param \Savvii\OpenproviderRest\Model\SettingsPaymentMethods[]|null $payment_methods payment_methods
     *
     * @return self
     */
    public function setPaymentMethods($payment_methods)
    {
        if (is_null($payment_methods)) {
            throw new \InvalidArgumentException('non-nullable payment_methods cannot be null');
        }
        $this->container['payment_methods'] = $payment_methods;

        return $this;
    }

    /**
     * Gets preregistered_domain_priorities
     *
     * @return string|null
     */
    public function getPreregisteredDomainPriorities()
    {
        return $this->container['preregistered_domain_priorities'];
    }

    /**
     * Sets preregistered_domain_priorities
     *
     * @param string|null $preregistered_domain_priorities preregistered_domain_priorities
     *
     * @return self
     */
    public function setPreregisteredDomainPriorities($preregistered_domain_priorities)
    {
        if (is_null($preregistered_domain_priorities)) {
            throw new \InvalidArgumentException('non-nullable preregistered_domain_priorities cannot be null');
        }
        $this->container['preregistered_domain_priorities'] = $preregistered_domain_priorities;

        return $this;
    }

    /**
     * Gets recurring_payment_methods
     *
     * @return \Savvii\OpenproviderRest\Model\SettingsPaymentMethods[]|null
     */
    public function getRecurringPaymentMethods()
    {
        return $this->container['recurring_payment_methods'];
    }

    /**
     * Sets recurring_payment_methods
     *
     * @param \Savvii\OpenproviderRest\Model\SettingsPaymentMethods[]|null $recurring_payment_methods recurring_payment_methods
     *
     * @return self
     */
    public function setRecurringPaymentMethods($recurring_payment_methods)
    {
        if (is_null($recurring_payment_methods)) {
            throw new \InvalidArgumentException('non-nullable recurring_payment_methods cannot be null');
        }
        $this->container['recurring_payment_methods'] = $recurring_payment_methods;

        return $this;
    }

    /**
     * Gets renew_notification_days
     *
     * @return int[]|null
     */
    public function getRenewNotificationDays()
    {
        return $this->container['renew_notification_days'];
    }

    /**
     * Sets renew_notification_days
     *
     * @param int[]|null $renew_notification_days renew_notification_days
     *
     * @return self
     */
    public function setRenewNotificationDays($renew_notification_days)
    {
        if (is_null($renew_notification_days)) {
            throw new \InvalidArgumentException('non-nullable renew_notification_days cannot be null');
        }
        $this->container['renew_notification_days'] = $renew_notification_days;

        return $this;
    }

    /**
     * Gets renew_notification_every_week
     *
     * @return bool|null
     */
    public function getRenewNotificationEveryWeek()
    {
        return $this->container['renew_notification_every_week'];
    }

    /**
     * Sets renew_notification_every_week
     *
     * @param bool|null $renew_notification_every_week renew_notification_every_week
     *
     * @return self
     */
    public function setRenewNotificationEveryWeek($renew_notification_every_week)
    {
        if (is_null($renew_notification_every_week)) {
            throw new \InvalidArgumentException('non-nullable renew_notification_every_week cannot be null');
        }
        $this->container['renew_notification_every_week'] = $renew_notification_every_week;

        return $this;
    }

    /**
     * Gets signed_contracts
     *
     * @return \Savvii\OpenproviderRest\Model\SettingsSignedContracts[]|null
     */
    public function getSignedContracts()
    {
        return $this->container['signed_contracts'];
    }

    /**
     * Sets signed_contracts
     *
     * @param \Savvii\OpenproviderRest\Model\SettingsSignedContracts[]|null $signed_contracts signed_contracts
     *
     * @return self
     */
    public function setSignedContracts($signed_contracts)
    {
        if (is_null($signed_contracts)) {
            throw new \InvalidArgumentException('non-nullable signed_contracts cannot be null');
        }
        $this->container['signed_contracts'] = $signed_contracts;

        return $this;
    }

    /**
     * Gets tac_contract
     *
     * @return \Savvii\OpenproviderRest\Model\SettingsTacContract|null
     */
    public function getTacContract()
    {
        return $this->container['tac_contract'];
    }

    /**
     * Sets tac_contract
     *
     * @param \Savvii\OpenproviderRest\Model\SettingsTacContract|null $tac_contract tac_contract
     *
     * @return self
     */
    public function setTacContract($tac_contract)
    {
        if (is_null($tac_contract)) {
            throw new \InvalidArgumentException('non-nullable tac_contract cannot be null');
        }
        $this->container['tac_contract'] = $tac_contract;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets transaction_fee
     *
     * @return \Savvii\OpenproviderRest\Model\SettingsTransactionFee|null
     */
    public function getTransactionFee()
    {
        return $this->container['transaction_fee'];
    }

    /**
     * Sets transaction_fee
     *
     * @param \Savvii\OpenproviderRest\Model\SettingsTransactionFee|null $transaction_fee transaction_fee
     *
     * @return self
     */
    public function setTransactionFee($transaction_fee)
    {
        if (is_null($transaction_fee)) {
            throw new \InvalidArgumentException('non-nullable transaction_fee cannot be null');
        }
        $this->container['transaction_fee'] = $transaction_fee;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


