<?php
/**
 * SeDomainProductsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Savvii\OpenproviderRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Savvii\OpenproviderRest\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SeDomainProductsTest Class Doc Comment
 *
 * @category    Class
 * @description SeDomainProducts
 * @package     Savvii\OpenproviderRest
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SeDomainProductsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SeDomainProducts"
     */
    public function testSeDomainProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "archiving"
     */
    public function testPropertyArchiving()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "incoming"
     */
    public function testPropertyIncoming()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "outgoing"
     */
    public function testPropertyOutgoing()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
