<?php
/**
 * TemplateServiceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Savvii\OpenproviderRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Savvii\OpenproviderRest\Test\Api;

use \Savvii\OpenproviderRest\Configuration;
use \Savvii\OpenproviderRest\ApiException;
use \Savvii\OpenproviderRest\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TemplateServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Savvii\OpenproviderRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TemplateServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createTemplate
     *
     * Create template.
     *
     */
    public function testCreateTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteTemplate
     *
     * Delete template.
     *
     */
    public function testDeleteTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTemplate
     *
     * Get template.
     *
     */
    public function testGetTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTemplates
     *
     * List templates.
     *
     */
    public function testListTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
